/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.7 */

#ifndef PB_APP_PB_MSG_SET_PB_H_INCLUDED
#define PB_APP_PB_MSG_SET_PB_H_INCLUDED
#include <pb.h>
#include "app_pb_msg_mix.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
/* 组合消息类型 */
typedef enum _AppPB_MsgSet_Type {
    AppPB_MsgSet_Type_Is_Default = 0,
    AppPB_MsgSet_Type_Is_SystemClock = 16,
    AppPB_MsgSet_Type_Is_TraceText = 17,
    AppPB_MsgSet_Type_Is_WorldClock = 257
} AppPB_MsgSet_Type;

/* Struct definitions */
/* 组合消息(所有nanopb子消息打包成一个整体) */
typedef struct _AppPB_MsgSet {
    /* 组合消息 */
    AppPB_MsgSet_Type type;
    pb_size_t which_payload;
    union {
        AppPB_SystemClock system_clock;
        AppPB_TraceText trace_text;
        AppPB_WorldClock world_clock;
    } payload;
} AppPB_MsgSet;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _AppPB_MsgSet_Type_MIN AppPB_MsgSet_Type_Is_Default
#define _AppPB_MsgSet_Type_MAX AppPB_MsgSet_Type_Is_WorldClock
#define _AppPB_MsgSet_Type_ARRAYSIZE ((AppPB_MsgSet_Type)(AppPB_MsgSet_Type_Is_WorldClock+1))

#define AppPB_MsgSet_type_ENUMTYPE AppPB_MsgSet_Type


/* Initializer values for message structs */
#define AppPB_MsgSet_init_default                {_AppPB_MsgSet_Type_MIN, 0, {AppPB_SystemClock_init_default}}
#define AppPB_MsgSet_init_zero                   {_AppPB_MsgSet_Type_MIN, 0, {AppPB_SystemClock_init_zero}}

/* Field tags (for use in manual encoding/decoding) */
#define AppPB_MsgSet_type_tag                    1
#define AppPB_MsgSet_system_clock_tag            16
#define AppPB_MsgSet_trace_text_tag              17
#define AppPB_MsgSet_world_clock_tag             257

/* Struct field encoding specification for nanopb */
#define AppPB_MsgSet_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, UENUM,    type,              1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,system_clock,payload.system_clock),  16) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,trace_text,payload.trace_text),  17) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,world_clock,payload.world_clock), 257)
#define AppPB_MsgSet_CALLBACK NULL
#define AppPB_MsgSet_DEFAULT NULL
#define AppPB_MsgSet_payload_system_clock_MSGTYPE AppPB_SystemClock
#define AppPB_MsgSet_payload_trace_text_MSGTYPE AppPB_TraceText
#define AppPB_MsgSet_payload_world_clock_MSGTYPE AppPB_WorldClock

extern const pb_msgdesc_t AppPB_MsgSet_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define AppPB_MsgSet_fields &AppPB_MsgSet_msg

/* Maximum encoded size of messages (where known) */
#define AppPB_MsgSet_size                        144

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
