/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.7 */

#ifndef PB_APP_PB_MSG_MIX_PB_H_INCLUDED
#define PB_APP_PB_MSG_MIX_PB_H_INCLUDED
#include <pb.h>
#include "nanopb/nanopb.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
/* 系统时钟制式 */
typedef enum _AppPB_SystemClock_Mode {
    AppPB_SystemClock_Mode_IS_12 = 0,
    AppPB_SystemClock_Mode_IS_24 = 1
} AppPB_SystemClock_Mode;

/* Struct definitions */
/* 系统时钟消息(日历时间) */
typedef struct _AppPB_SystemClock {
    uint16_t year; /* 年(UTC的0时区) */
    uint8_t month; /* 月(UTC的0时区) */
    uint8_t day; /* 日(UTC的0时区) */
    uint8_t hour; /* 时(UTC的0时区) */
    uint8_t minute; /* 分(UTC的0时区) */
    uint8_t second; /* 秒(UTC的0时区) */
    int32_t zone; /* 时区偏移(秒),带符号 */
    AppPB_SystemClock_Mode mode;
} AppPB_SystemClock;

/* 世界时钟消息 */
typedef struct _AppPB_WorldClock {
    char *city_name; /* 城市名称 */
    int32_t zone_offset; /* 时区偏移(秒),带符号 */
    double longitude; /* 经度:东经+,西经- */
    double latitude; /* 维度:北纬+,南纬- */
    bool has_city_id;
    uint32_t city_id; /* 城市ID */
} AppPB_WorldClock;

/* 世界时钟列表 */
typedef struct _AppPB_WorldClock_List {
    pb_size_t node_count;
    struct _AppPB_WorldClock *node;
} AppPB_WorldClock_List;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _AppPB_SystemClock_Mode_MIN AppPB_SystemClock_Mode_IS_12
#define _AppPB_SystemClock_Mode_MAX AppPB_SystemClock_Mode_IS_24
#define _AppPB_SystemClock_Mode_ARRAYSIZE ((AppPB_SystemClock_Mode)(AppPB_SystemClock_Mode_IS_24+1))

#define AppPB_SystemClock_mode_ENUMTYPE AppPB_SystemClock_Mode




/* Initializer values for message structs */
#define AppPB_SystemClock_init_default           {2023ull, 1ull, 1ull, 0ull, 0ull, 0ull, 28800, AppPB_SystemClock_Mode_IS_24}
#define AppPB_WorldClock_init_default            {NULL, 28800, 116.2, 39.56, false, 0}
#define AppPB_WorldClock_List_init_default       {0, NULL}
#define AppPB_SystemClock_init_zero              {0, 0, 0, 0, 0, 0, 0, _AppPB_SystemClock_Mode_MIN}
#define AppPB_WorldClock_init_zero               {NULL, 0, 0, 0, false, 0}
#define AppPB_WorldClock_List_init_zero          {0, NULL}

/* Field tags (for use in manual encoding/decoding) */
#define AppPB_SystemClock_year_tag               1
#define AppPB_SystemClock_month_tag              2
#define AppPB_SystemClock_day_tag                3
#define AppPB_SystemClock_hour_tag               4
#define AppPB_SystemClock_minute_tag             5
#define AppPB_SystemClock_second_tag             6
#define AppPB_SystemClock_zone_tag               7
#define AppPB_SystemClock_mode_tag               8
#define AppPB_WorldClock_city_name_tag           1
#define AppPB_WorldClock_zone_offset_tag         2
#define AppPB_WorldClock_longitude_tag           3
#define AppPB_WorldClock_latitude_tag            4
#define AppPB_WorldClock_city_id_tag             5
#define AppPB_WorldClock_List_node_tag           1

/* Struct field encoding specification for nanopb */
#define AppPB_SystemClock_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, UINT64,   year,              1) \
X(a, STATIC,   REQUIRED, UINT64,   month,             2) \
X(a, STATIC,   REQUIRED, UINT64,   day,               3) \
X(a, STATIC,   REQUIRED, UINT64,   hour,              4) \
X(a, STATIC,   REQUIRED, UINT64,   minute,            5) \
X(a, STATIC,   REQUIRED, UINT64,   second,            6) \
X(a, STATIC,   REQUIRED, SINT64,   zone,              7) \
X(a, STATIC,   REQUIRED, UENUM,    mode,              8)
#define AppPB_SystemClock_CALLBACK NULL
#define AppPB_SystemClock_DEFAULT (const pb_byte_t*)"\x08\xe7\x0f\x10\x01\x18\x01\x20\x00\x28\x00\x30\x00\x38\x80\xc2\x03\x40\x01\x00"

#define AppPB_WorldClock_FIELDLIST(X, a) \
X(a, POINTER,  REQUIRED, STRING,   city_name,         1) \
X(a, STATIC,   REQUIRED, SINT64,   zone_offset,       2) \
X(a, STATIC,   REQUIRED, DOUBLE,   longitude,         3) \
X(a, STATIC,   REQUIRED, DOUBLE,   latitude,          4) \
X(a, STATIC,   OPTIONAL, UINT32,   city_id,           5)
#define AppPB_WorldClock_CALLBACK NULL
#define AppPB_WorldClock_DEFAULT (const pb_byte_t*)"\x10\x80\xc2\x03\x19\xcd\xcc\xcc\xcc\xcc\x0c\x5d\x40\x21\x48\xe1\x7a\x14\xae\xc7\x43\x40\x00"

#define AppPB_WorldClock_List_FIELDLIST(X, a) \
X(a, POINTER,  REPEATED, MESSAGE,  node,              1)
#define AppPB_WorldClock_List_CALLBACK NULL
#define AppPB_WorldClock_List_DEFAULT NULL
#define AppPB_WorldClock_List_node_MSGTYPE AppPB_WorldClock

extern const pb_msgdesc_t AppPB_SystemClock_msg;
extern const pb_msgdesc_t AppPB_WorldClock_msg;
extern const pb_msgdesc_t AppPB_WorldClock_List_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define AppPB_SystemClock_fields &AppPB_SystemClock_msg
#define AppPB_WorldClock_fields &AppPB_WorldClock_msg
#define AppPB_WorldClock_List_fields &AppPB_WorldClock_List_msg

/* Maximum encoded size of messages (where known) */
/* AppPB_WorldClock_size depends on runtime parameters */
/* AppPB_WorldClock_List_size depends on runtime parameters */
#define AppPB_SystemClock_size                   27

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
