/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.7 */

#ifndef PB_APP_PB_MSG_SET_PB_H_INCLUDED
#define PB_APP_PB_MSG_SET_PB_H_INCLUDED
#include <pb.h>
#include "nanopb/nanopb.pb.h"
#include "app_pb_msg_mix.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
/* 组合消息类型 */
typedef enum _AppPB_MsgTypeSet {
    AppPB_MsgTypeSet_AppPB_MsgType_Is_Default = 0,
    AppPB_MsgTypeSet_AppPB_MsgType_Is_SystemClock = 16,
    AppPB_MsgTypeSet_AppPB_MsgType_Is_WorldClock = 17
} AppPB_MsgTypeSet;

/* Struct definitions */
/* 组合消息(通过不同的消息特征编号区分不同的消息) */
typedef struct _AppPB_MsgSet {
    AppPB_MsgTypeSet type;
    pb_size_t which_payload;
    union {
        AppPB_SystemClock system_clock;
        AppPB_WorldClock world_clock;
    } payload;
} AppPB_MsgSet;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _AppPB_MsgTypeSet_MIN AppPB_MsgTypeSet_AppPB_MsgType_Is_Default
#define _AppPB_MsgTypeSet_MAX AppPB_MsgTypeSet_AppPB_MsgType_Is_WorldClock
#define _AppPB_MsgTypeSet_ARRAYSIZE ((AppPB_MsgTypeSet)(AppPB_MsgTypeSet_AppPB_MsgType_Is_WorldClock+1))

#define AppPB_MsgSet_type_ENUMTYPE AppPB_MsgTypeSet


/* Initializer values for message structs */
#define AppPB_MsgSet_init_default                {_AppPB_MsgTypeSet_MIN, 0, {AppPB_SystemClock_init_default}}
#define AppPB_MsgSet_init_zero                   {_AppPB_MsgTypeSet_MIN, 0, {AppPB_SystemClock_init_zero}}

/* Field tags (for use in manual encoding/decoding) */
#define AppPB_MsgSet_type_tag                    1
#define AppPB_MsgSet_system_clock_tag            20
#define AppPB_MsgSet_world_clock_tag             21

/* Struct field encoding specification for nanopb */
#define AppPB_MsgSet_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, UENUM,    type,              1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,system_clock,payload.system_clock),  20) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,world_clock,payload.world_clock),  21)
#define AppPB_MsgSet_CALLBACK NULL
#define AppPB_MsgSet_DEFAULT NULL
#define AppPB_MsgSet_payload_system_clock_MSGTYPE AppPB_SystemClock
#define AppPB_MsgSet_payload_world_clock_MSGTYPE AppPB_WorldClock

extern const pb_msgdesc_t AppPB_MsgSet_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define AppPB_MsgSet_fields &AppPB_MsgSet_msg

/* Maximum encoded size of messages (where known) */
#if defined(AppPB_WorldClock_size)
union AppPB_MsgSet_payload_size_union {char f21[(7 + AppPB_WorldClock_size)]; char f0[30];};
#endif
#if defined(AppPB_WorldClock_size)
#define AppPB_MsgSet_size                        (2 + sizeof(union AppPB_MsgSet_payload_size_union))
#endif

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
