/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.7 */

#include "app_nanopb_flie.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(AppPB_FileDes, AppPB_FileDes, 2)


PB_BIND(AppPB_FilePkg, AppPB_FilePkg, 2)


PB_BIND(AppPB_FileEnd, AppPB_FileEnd, AUTO)


PB_BIND(AppPB_File, AppPB_File, 2)


PB_BIND(AppPB_Ota, AppPB_Ota, AUTO)



