/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.7 */

#ifndef PB_APP_NANOPB_FUNC_PB_H_INCLUDED
#define PB_APP_NANOPB_FUNC_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
/* 系统时钟制式 */
typedef enum _AppPB_SysClock_Mode {
    AppPB_SysClock_Mode_IS_24 = 0,
    AppPB_SysClock_Mode_IS_12 = 1
} AppPB_SysClock_Mode;

/* Struct definitions */
/* 系统消息:设备信息(UTE 0xA4) */
typedef struct _AppPB_DevInfo {
    char model[16]; /* 设备型号 */
    char hw_ver[16]; /* 硬件版本 */
    char sw_ver[16]; /* 软件版本 */
    char sn[32]; /* 序列号 */
    char bt_addr[32]; /* 蓝牙地址 */
    char pid[16]; /* 产品ID */
    uint8_t battery; /* 电量 */
} AppPB_DevInfo;

/* 系统消息:设备参数(UTE 0xA5) */
typedef struct _AppPB_DevParam {
    uint8_t lang_id; /* 语言ID */
    uint32_t zone; /* 时区 */
    uint8_t is_12h; /* 12/24小时制 */
    uint8_t is_mi; /* 距离单位(英里) */
    uint8_t brt; /* 屏幕亮度 */
} AppPB_DevParam;

/* 系统消息:电子保卡(UTE 0xA2) */
typedef struct _AppPB_ElecCard {
    bool is_activate; /* 是否已激活 */
    bool is_reported; /* 是否已上报 */
} AppPB_ElecCard;

/* 闹钟消息(UTE 0xC7, 最多MAX_ALARM_SUPPORT=5组) */
typedef struct _AppPB_Alarm {
    uint8_t index; /* 闹钟索引 */
    uint8_t repeat; /* 重复日bit0周日..bit6周六 */
    uint8_t on; /* 开关 */
    uint8_t hour; /* 小时 */
    uint8_t min; /* 分钟 */
    char name[128]; /* 名字 */
} AppPB_Alarm;

/* 未来单天天气 */
typedef struct _AppPB_WeatherDay {
    int16_t temp_max; /* 最高气温 */
    int16_t temp_min; /* 最低气温 */
    uint8_t phen; /* 天气现象 */
    uint8_t humi; /* 湿度 */
} AppPB_WeatherDay;

/* 天气消息(UTE 0xE0) */
typedef struct _AppPB_Weather {
    int16_t temp_cur; /* 当前气温 */
    int16_t temp_max; /* 最高气温 */
    int16_t temp_min; /* 最低气温 */
    uint8_t phen; /* 天气现象 */
    uint8_t humi; /* 湿度 */
    uint8_t uv; /* 紫外线 */
    int16_t pm25; /* PM2.5 */
    int16_t aqi; /* 空气质量 */
    char city[64]; /* 城市 */
    pb_size_t day_count;
    AppPB_WeatherDay day[7]; /* 未来7天 */
} AppPB_Weather;

/* 勿扰消息(UTE 0xEA) */
typedef struct _AppPB_NotDisturb {
    uint8_t on; /* 勿扰开关 */
    uint8_t shour; /* 开始小时 */
    uint8_t smin; /* 开始分钟 */
    uint8_t ehour; /* 结束小时 */
    uint8_t emin; /* 结束分钟 */
    uint8_t repeat; /* 重复日 */
} AppPB_NotDisturb;

/* 心率参数消息(UTE 0xE1) */
typedef struct _AppPB_HeartRate {
    uint8_t is_auto; /* 自动测量开关 */
    uint8_t lwarn_on; /* 低心率提醒开关 */
    uint8_t hwarn_on; /* 高心率提醒开关 */
    uint8_t lwarn; /* 低提醒值 */
    uint8_t hwarn; /* 高提醒值 */
    uint16_t test_min; /* 自动测试间隔(分钟) */
    uint8_t static_type; /* 静态心率类型 */
} AppPB_HeartRate;

/* 音乐消息(UTE 0xE2) */
typedef struct _AppPB_Music {
    char singer[64]; /* 歌手 */
    char song_name[64]; /* 曲名 */
    uint8_t play_st; /* 播放状态 */
    uint8_t max_vol; /* 最大音量 */
    uint8_t cur_vol; /* 当前音量 */
    uint8_t app_st; /* app状态 */
} AppPB_Music;

/* 消息通知(UTE 0xB0~B3) */
typedef struct _AppPB_MsgInfo {
    char app_name[64]; /* 应用名 */
    char contact[64]; /* 联系人 */
    char content[128]; /* 内容 */
    uint8_t msg_id; /* 消息ID */
    char phone[32]; /* 电话 */
    uint8_t msg_type; /* 消息类型 */
    uint8_t vibrate; /* 震动开关 */
} AppPB_MsgInfo;

/* 联系人(UTE 0xC0) */
typedef struct _AppPB_Contact {
    char name[128]; /* 联系人名 */
    uint16_t name_len; /* 名字长度 */
    char phone[32]; /* 号码 */
    uint16_t phone_len; /* 号码长度 */
    uint8_t state; /* 接听/挂断 */
} AppPB_Contact;

/* 运动目标(UTE 0xC1) */
typedef struct _AppPB_SportTgt {
    uint8_t motion_t; /* 运动类型 */
    uint8_t goal_type; /* 目标类型 */
    uint32_t step; /* 目标步数 */
    uint32_t kcal; /* 目标卡路里 */
    uint32_t meter; /* 目标距离(米) */
    uint32_t duration; /* 目标时长 */
} AppPB_SportTgt;

/* 用户身体信息(UTE 0xC2) */
typedef struct _AppPB_UserPhys {
    uint8_t age; /* 年龄 */
    uint32_t birthday; /* 生日(时间戳) */
    uint8_t gender; /* 性别 */
    uint32_t height; /* 身高(cm) */
    uint32_t weight; /* 体重 */
    uint32_t vo2max; /* 最大摄氧量 */
    uint32_t run_step; /* 跑步步长 */
    uint32_t walk_step; /* 走路步长 */
} AppPB_UserPhys;

/* 运动汇总(UTE 0xC3) */
typedef struct _AppPB_MotionSum {
    uint8_t hr_value; /* 最后心率值 */
    uint32_t hr_ts; /* 心率时间戳 */
    uint32_t kcal; /* 卡路里 */
    uint32_t distance; /* 距离 */
    uint32_t elevation; /* 爬升 */
    uint32_t sleep_time; /* 睡眠时长 */
    uint32_t step; /* 步数 */
} AppPB_MotionSum;

/* 运动状态(UTE 0xE5) */
typedef struct _AppPB_SportState {
    uint8_t monitor_st; /* 监测占用 */
    uint8_t operator_t; /* 执行类型 */
    uint8_t sport_type; /* 运动分类 */
    uint32_t start_time; /* 开始时间 */
    uint8_t workout_type; /* 单次运动类型 */
    uint32_t op_time; /* 操作时间 */
} AppPB_SportState;

/* 地理位置(UTE 0xE9) */
typedef struct _AppPB_Position {
    uint8_t speed; /* 速度(dm/s) */
    uint16_t distance; /* 距离(分米) */
    int16_t altitude; /* 海拔(米) */
    uint32_t total_dist; /* 总距离(分米) */
    uint32_t start_time; /* 开始时间 */
    uint32_t end_time; /* 结束时间 */
    int32_t latitude; /* 纬度(WGS84 1e-7) */
    int32_t longitude; /* 经度(WGS84 1e-7) */
    uint16_t bearing; /* 方向0~360 */
    uint16_t accuracy; /* 精度(米) */
} AppPB_Position;

/* 生理周期(UTE 0xE6) */
typedef struct _AppPB_FemCycle {
    uint8_t remind_sw; /* 总开关 */
    uint8_t menstr_remind; /* 经期开始提醒 */
    uint8_t menstr_end_remind; /* 经期结束提醒 */
    uint8_t ovulat_remind; /* 易孕开始提醒 */
    uint8_t ovulat_end_remind; /* 易孕结束提醒 */
    uint32_t cycle_start; /* 经期开始时间 */
    uint32_t cycle_end; /* 经期结束时间 */
    uint8_t keep_days; /* 持续天数 */
    uint16_t cycle_days; /* 周期天数 */
} AppPB_FemCycle;

/* 账户(UTE 0xE7) */
typedef struct _AppPB_Account {
    char account[255]; /* 账号 */
    uint8_t acc_len; /* 账号长度 */
    uint8_t pair_state; /* 配对状态 */
    uint8_t app_role; /* app角色 */
} AppPB_Account;

/* 运动管理(UTE 0xEC) */
typedef struct _AppPB_SportMng {
    uint8_t max_add_num; /* 最大可添加数 */
    uint8_t min_add_num; /* 最小可添加数 */
    pb_size_t sport_type_count;
    uint64_t sport_type[32]; /* 运动类型列表 */
} AppPB_SportMng;

/* 运动记录(UTE 0xE8) */
typedef struct _AppPB_SportRcd {
    uint16_t id; /* 记录ID */
    uint8_t status; /* 状态 */
    uint32_t start_time; /* 开始时间 */
    uint32_t end_time; /* 结束时间 */
    uint32_t calorie; /* 卡路里 */
    uint32_t distance; /* 距离(米) */
    uint32_t step; /* 步数 */
    uint32_t duration; /* 时长(秒) */
    uint16_t speed; /* 速度 */
    uint8_t type; /* 运动类型 */
} AppPB_SportRcd;

/* 系统时钟消息(日历时间) */
typedef struct _AppPB_SysClock {
    uint16_t year; /* 年(UTC的0时区) */
    uint8_t month; /* 月(UTC的0时区) */
    uint8_t day; /* 日(UTC的0时区) */
    uint8_t hour; /* 时(UTC的0时区) */
    uint8_t minute; /* 分(UTC的0时区) */
    uint8_t second; /* 秒(UTC的0时区) */
    int32_t zone; /* 时区偏移(秒),带符号 */
    AppPB_SysClock_Mode mode; /* 系统时钟制式 */
} AppPB_SysClock;

/* 世界时钟消息 */
typedef struct _AppPB_WorldClock {
    uint8_t now_index; /* 世界时钟当前索引 */
    uint8_t max_count; /* 世界时钟数量 */
    char city_name[100]; /* 城市名称 */
    int32_t zone_offset; /* 时区偏移(秒),带符号 */
    double longitude; /* 经度:东经+,西经- */
    double latitude; /* 维度:北纬+,南纬- */
    uint32_t city_id; /* 城市ID */
} AppPB_WorldClock;

/* 显示与菜单消息(UTE auxiliary/displayinfo) */
typedef struct _AppPB_DisplayInfo {
    uint8_t display_off_sec; /* 熄屏时间 */
    uint8_t backlight; /* 背光亮度 */
    uint8_t last_brt; /* 上次背光 */
    uint8_t theme_screen; /* 菜单主题 */
    uint8_t effect_style; /* 切换特效 */
    uint8_t interface_style; /* 一级菜单特效 */
    uint8_t jump_home; /* 跳回首页 */
    uint8_t dial_lock; /* 表盘切换锁 */
} AppPB_DisplayInfo;

/* App绑定消息(UTE appBinding) */
typedef struct _AppPB_AppBind {
    uint32_t new_bind_uid; /* 新绑定用户ID */
    uint32_t save_bind_uid; /* 已保存用户ID */
    uint32_t qr_random; /* 二维码随机码 */
    uint8_t conn_before; /* 曾经连接过 */
    uint8_t bind_notify; /* 有绑定通知 */
    uint8_t our_app_conn; /* 已连自家APP */
    uint8_t bind_start; /* 正在绑定 */
    uint8_t disp_screen; /* 已显示二维码 */
    uint8_t conn_sec_cnt; /* 连接秒计数 */
} AppPB_AppBind;

/* 省电/影院/运动识别消息(UTE powerSavingInfo/theaterInfo/motionRecoInfo) */
typedef struct _AppPB_Power {
    uint8_t power_save; /* 省电模式 */
    uint8_t everbright; /* 屏幕常亮 */
    uint8_t hr_auto; /* 省电下心率自动 */
    uint8_t spo2_auto; /* 省电下血氧自动 */
    uint8_t pressure_auto; /* 省电下压力自动 */
    uint8_t emotion_auto; /* 省电下情绪自动 */
    uint8_t theater; /* 影院模式 */
    uint8_t motion_reco; /* 运动识别 */
} AppPB_Power;

/* 单天作息 */
typedef struct _AppPB_SleepSet_Schedule {
    uint8_t day_of_week; /* 有效星期 */
    uint8_t fall_hour; /* 入睡时 */
    uint8_t fall_min; /* 入睡分 */
    uint8_t wake_hour; /* 起床时 */
    uint8_t wake_min; /* 起床分 */
    uint8_t is_alarm; /* 是否到闹钟 */
} AppPB_SleepSet_Schedule;

/* 睡眠设置消息(UTE sleepSetting) */
typedef struct _AppPB_SleepSet {
    pb_size_t schedule_count;
    AppPB_SleepSet_Schedule schedule[7]; /* 7天作息 */
    uint8_t mode_switch; /* 睡眠模式开关 */
    uint8_t mode_status; /* 睡眠模式生效中 */
    uint16_t target_dur; /* 睡眠目标(min) */
    uint8_t remind_switch; /* 睡眠提醒开关 */
    uint16_t remind; /* 提前提醒(min) */
    uint8_t snooze_on; /* 贪睡开关 */
    uint32_t snooze_time; /* 贪睡时间 */
    uint8_t snooze_cnt; /* 贪睡次数 */
} AppPB_SleepSet;

/* 表盘配置消息(UTE watchConfigInfo/watchSortInfo) */
typedef struct _AppPB_WatchCfg {
    uint16_t pixel_width; /* 表盘宽 */
    uint16_t pixel_height; /* 表盘高 */
    uint32_t file_crc32; /* 表盘文件CRC32 */
    uint8_t cur_index; /* 当前表盘索引 */
    uint8_t aod_index; /* AOD表盘索引 */
    pb_size_t sort_count;
    uint64_t sort[8]; /* 表盘排序 */
} AppPB_WatchCfg;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _AppPB_SysClock_Mode_MIN AppPB_SysClock_Mode_IS_24
#define _AppPB_SysClock_Mode_MAX AppPB_SysClock_Mode_IS_12
#define _AppPB_SysClock_Mode_ARRAYSIZE ((AppPB_SysClock_Mode)(AppPB_SysClock_Mode_IS_12+1))





















#define AppPB_SysClock_mode_ENUMTYPE AppPB_SysClock_Mode









/* Initializer values for message structs */
#define AppPB_DevInfo_init_default               {"", "", "", "", "", "", 0}
#define AppPB_DevParam_init_default              {0, 0, 0, 0, 0}
#define AppPB_ElecCard_init_default              {0, 0}
#define AppPB_Alarm_init_default                 {0, 0, 0, 0, 0, ""}
#define AppPB_Weather_init_default               {0, 0, 0, 0, 0, 0, 0, 0, "", 0, {AppPB_WeatherDay_init_default, AppPB_WeatherDay_init_default, AppPB_WeatherDay_init_default, AppPB_WeatherDay_init_default, AppPB_WeatherDay_init_default, AppPB_WeatherDay_init_default, AppPB_WeatherDay_init_default}}
#define AppPB_WeatherDay_init_default            {0, 0, 0, 0}
#define AppPB_NotDisturb_init_default            {0, 0, 0, 0, 0, 0}
#define AppPB_HeartRate_init_default             {0, 0, 0, 0, 0, 0, 0}
#define AppPB_Music_init_default                 {"", "", 0, 0, 0, 0}
#define AppPB_MsgInfo_init_default               {"", "", "", 0, "", 0, 0}
#define AppPB_Contact_init_default               {"", 0, "", 0, 0}
#define AppPB_SportTgt_init_default              {0, 0, 0, 0, 0, 0}
#define AppPB_UserPhys_init_default              {0, 0, 0, 0, 0, 0, 0, 0}
#define AppPB_MotionSum_init_default             {0, 0, 0, 0, 0, 0, 0}
#define AppPB_SportState_init_default            {0, 0, 0, 0, 0, 0}
#define AppPB_Position_init_default              {0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define AppPB_FemCycle_init_default              {0, 0, 0, 0, 0, 0, 0, 0, 0}
#define AppPB_Account_init_default               {"", 0, 0, 0}
#define AppPB_SportMng_init_default              {0, 0, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}}
#define AppPB_SportRcd_init_default              {0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define AppPB_SysClock_init_default              {0, 0, 0, 0, 0, 0, 0, _AppPB_SysClock_Mode_MIN}
#define AppPB_WorldClock_init_default            {0, 0, "", 0, 0, 0, 0}
#define AppPB_DisplayInfo_init_default           {0, 0, 0, 0, 0, 0, 0, 0}
#define AppPB_AppBind_init_default               {0, 0, 0, 0, 0, 0, 0, 0, 0}
#define AppPB_Power_init_default                 {0, 0, 0, 0, 0, 0, 0, 0}
#define AppPB_SleepSet_init_default              {0, {AppPB_SleepSet_Schedule_init_default, AppPB_SleepSet_Schedule_init_default, AppPB_SleepSet_Schedule_init_default, AppPB_SleepSet_Schedule_init_default, AppPB_SleepSet_Schedule_init_default, AppPB_SleepSet_Schedule_init_default, AppPB_SleepSet_Schedule_init_default}, 0, 0, 0, 0, 0, 0, 0, 0}
#define AppPB_SleepSet_Schedule_init_default     {0, 0, 0, 0, 0, 0}
#define AppPB_WatchCfg_init_default              {0, 0, 0, 0, 0, 0, {0, 0, 0, 0, 0, 0, 0, 0}}
#define AppPB_DevInfo_init_zero                  {"", "", "", "", "", "", 0}
#define AppPB_DevParam_init_zero                 {0, 0, 0, 0, 0}
#define AppPB_ElecCard_init_zero                 {0, 0}
#define AppPB_Alarm_init_zero                    {0, 0, 0, 0, 0, ""}
#define AppPB_Weather_init_zero                  {0, 0, 0, 0, 0, 0, 0, 0, "", 0, {AppPB_WeatherDay_init_zero, AppPB_WeatherDay_init_zero, AppPB_WeatherDay_init_zero, AppPB_WeatherDay_init_zero, AppPB_WeatherDay_init_zero, AppPB_WeatherDay_init_zero, AppPB_WeatherDay_init_zero}}
#define AppPB_WeatherDay_init_zero               {0, 0, 0, 0}
#define AppPB_NotDisturb_init_zero               {0, 0, 0, 0, 0, 0}
#define AppPB_HeartRate_init_zero                {0, 0, 0, 0, 0, 0, 0}
#define AppPB_Music_init_zero                    {"", "", 0, 0, 0, 0}
#define AppPB_MsgInfo_init_zero                  {"", "", "", 0, "", 0, 0}
#define AppPB_Contact_init_zero                  {"", 0, "", 0, 0}
#define AppPB_SportTgt_init_zero                 {0, 0, 0, 0, 0, 0}
#define AppPB_UserPhys_init_zero                 {0, 0, 0, 0, 0, 0, 0, 0}
#define AppPB_MotionSum_init_zero                {0, 0, 0, 0, 0, 0, 0}
#define AppPB_SportState_init_zero               {0, 0, 0, 0, 0, 0}
#define AppPB_Position_init_zero                 {0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define AppPB_FemCycle_init_zero                 {0, 0, 0, 0, 0, 0, 0, 0, 0}
#define AppPB_Account_init_zero                  {"", 0, 0, 0}
#define AppPB_SportMng_init_zero                 {0, 0, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}}
#define AppPB_SportRcd_init_zero                 {0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define AppPB_SysClock_init_zero                 {0, 0, 0, 0, 0, 0, 0, _AppPB_SysClock_Mode_MIN}
#define AppPB_WorldClock_init_zero               {0, 0, "", 0, 0, 0, 0}
#define AppPB_DisplayInfo_init_zero              {0, 0, 0, 0, 0, 0, 0, 0}
#define AppPB_AppBind_init_zero                  {0, 0, 0, 0, 0, 0, 0, 0, 0}
#define AppPB_Power_init_zero                    {0, 0, 0, 0, 0, 0, 0, 0}
#define AppPB_SleepSet_init_zero                 {0, {AppPB_SleepSet_Schedule_init_zero, AppPB_SleepSet_Schedule_init_zero, AppPB_SleepSet_Schedule_init_zero, AppPB_SleepSet_Schedule_init_zero, AppPB_SleepSet_Schedule_init_zero, AppPB_SleepSet_Schedule_init_zero, AppPB_SleepSet_Schedule_init_zero}, 0, 0, 0, 0, 0, 0, 0, 0}
#define AppPB_SleepSet_Schedule_init_zero        {0, 0, 0, 0, 0, 0}
#define AppPB_WatchCfg_init_zero                 {0, 0, 0, 0, 0, 0, {0, 0, 0, 0, 0, 0, 0, 0}}

/* Field tags (for use in manual encoding/decoding) */
#define AppPB_DevInfo_model_tag                  1
#define AppPB_DevInfo_hw_ver_tag                 2
#define AppPB_DevInfo_sw_ver_tag                 3
#define AppPB_DevInfo_sn_tag                     4
#define AppPB_DevInfo_bt_addr_tag                5
#define AppPB_DevInfo_pid_tag                    6
#define AppPB_DevInfo_battery_tag                7
#define AppPB_DevParam_lang_id_tag               1
#define AppPB_DevParam_zone_tag                  2
#define AppPB_DevParam_is_12h_tag                3
#define AppPB_DevParam_is_mi_tag                 4
#define AppPB_DevParam_brt_tag                   5
#define AppPB_ElecCard_is_activate_tag           1
#define AppPB_ElecCard_is_reported_tag           2
#define AppPB_Alarm_index_tag                    1
#define AppPB_Alarm_repeat_tag                   2
#define AppPB_Alarm_on_tag                       3
#define AppPB_Alarm_hour_tag                     4
#define AppPB_Alarm_min_tag                      5
#define AppPB_Alarm_name_tag                     6
#define AppPB_WeatherDay_temp_max_tag            1
#define AppPB_WeatherDay_temp_min_tag            2
#define AppPB_WeatherDay_phen_tag                3
#define AppPB_WeatherDay_humi_tag                4
#define AppPB_Weather_temp_cur_tag               1
#define AppPB_Weather_temp_max_tag               2
#define AppPB_Weather_temp_min_tag               3
#define AppPB_Weather_phen_tag                   4
#define AppPB_Weather_humi_tag                   5
#define AppPB_Weather_uv_tag                     6
#define AppPB_Weather_pm25_tag                   7
#define AppPB_Weather_aqi_tag                    8
#define AppPB_Weather_city_tag                   9
#define AppPB_Weather_day_tag                    10
#define AppPB_NotDisturb_on_tag                  1
#define AppPB_NotDisturb_shour_tag               2
#define AppPB_NotDisturb_smin_tag                3
#define AppPB_NotDisturb_ehour_tag               4
#define AppPB_NotDisturb_emin_tag                5
#define AppPB_NotDisturb_repeat_tag              6
#define AppPB_HeartRate_is_auto_tag              1
#define AppPB_HeartRate_lwarn_on_tag             2
#define AppPB_HeartRate_hwarn_on_tag             3
#define AppPB_HeartRate_lwarn_tag                4
#define AppPB_HeartRate_hwarn_tag                5
#define AppPB_HeartRate_test_min_tag             6
#define AppPB_HeartRate_static_type_tag          7
#define AppPB_Music_singer_tag                   1
#define AppPB_Music_song_name_tag                2
#define AppPB_Music_play_st_tag                  3
#define AppPB_Music_max_vol_tag                  4
#define AppPB_Music_cur_vol_tag                  5
#define AppPB_Music_app_st_tag                   6
#define AppPB_MsgInfo_app_name_tag               1
#define AppPB_MsgInfo_contact_tag                2
#define AppPB_MsgInfo_content_tag                3
#define AppPB_MsgInfo_msg_id_tag                 4
#define AppPB_MsgInfo_phone_tag                  5
#define AppPB_MsgInfo_msg_type_tag               6
#define AppPB_MsgInfo_vibrate_tag                7
#define AppPB_Contact_name_tag                   1
#define AppPB_Contact_name_len_tag               2
#define AppPB_Contact_phone_tag                  3
#define AppPB_Contact_phone_len_tag              4
#define AppPB_Contact_state_tag                  5
#define AppPB_SportTgt_motion_t_tag              1
#define AppPB_SportTgt_goal_type_tag             2
#define AppPB_SportTgt_step_tag                  3
#define AppPB_SportTgt_kcal_tag                  4
#define AppPB_SportTgt_meter_tag                 5
#define AppPB_SportTgt_duration_tag              6
#define AppPB_UserPhys_age_tag                   1
#define AppPB_UserPhys_birthday_tag              2
#define AppPB_UserPhys_gender_tag                3
#define AppPB_UserPhys_height_tag                4
#define AppPB_UserPhys_weight_tag                5
#define AppPB_UserPhys_vo2max_tag                6
#define AppPB_UserPhys_run_step_tag              7
#define AppPB_UserPhys_walk_step_tag             8
#define AppPB_MotionSum_hr_value_tag             1
#define AppPB_MotionSum_hr_ts_tag                2
#define AppPB_MotionSum_kcal_tag                 3
#define AppPB_MotionSum_distance_tag             4
#define AppPB_MotionSum_elevation_tag            5
#define AppPB_MotionSum_sleep_time_tag           6
#define AppPB_MotionSum_step_tag                 7
#define AppPB_SportState_monitor_st_tag          1
#define AppPB_SportState_operator_t_tag          2
#define AppPB_SportState_sport_type_tag          3
#define AppPB_SportState_start_time_tag          4
#define AppPB_SportState_workout_type_tag        5
#define AppPB_SportState_op_time_tag             6
#define AppPB_Position_speed_tag                 1
#define AppPB_Position_distance_tag              2
#define AppPB_Position_altitude_tag              3
#define AppPB_Position_total_dist_tag            4
#define AppPB_Position_start_time_tag            5
#define AppPB_Position_end_time_tag              6
#define AppPB_Position_latitude_tag              7
#define AppPB_Position_longitude_tag             8
#define AppPB_Position_bearing_tag               9
#define AppPB_Position_accuracy_tag              10
#define AppPB_FemCycle_remind_sw_tag             1
#define AppPB_FemCycle_menstr_remind_tag         2
#define AppPB_FemCycle_menstr_end_remind_tag     3
#define AppPB_FemCycle_ovulat_remind_tag         4
#define AppPB_FemCycle_ovulat_end_remind_tag     5
#define AppPB_FemCycle_cycle_start_tag           6
#define AppPB_FemCycle_cycle_end_tag             7
#define AppPB_FemCycle_keep_days_tag             8
#define AppPB_FemCycle_cycle_days_tag            9
#define AppPB_Account_account_tag                1
#define AppPB_Account_acc_len_tag                2
#define AppPB_Account_pair_state_tag             3
#define AppPB_Account_app_role_tag               4
#define AppPB_SportMng_max_add_num_tag           1
#define AppPB_SportMng_min_add_num_tag           2
#define AppPB_SportMng_sport_type_tag            3
#define AppPB_SportRcd_id_tag                    1
#define AppPB_SportRcd_status_tag                2
#define AppPB_SportRcd_start_time_tag            3
#define AppPB_SportRcd_end_time_tag              4
#define AppPB_SportRcd_calorie_tag               5
#define AppPB_SportRcd_distance_tag              6
#define AppPB_SportRcd_step_tag                  7
#define AppPB_SportRcd_duration_tag              8
#define AppPB_SportRcd_speed_tag                 9
#define AppPB_SportRcd_type_tag                  10
#define AppPB_SysClock_year_tag                  1
#define AppPB_SysClock_month_tag                 2
#define AppPB_SysClock_day_tag                   3
#define AppPB_SysClock_hour_tag                  4
#define AppPB_SysClock_minute_tag                5
#define AppPB_SysClock_second_tag                6
#define AppPB_SysClock_zone_tag                  7
#define AppPB_SysClock_mode_tag                  8
#define AppPB_WorldClock_now_index_tag           1
#define AppPB_WorldClock_max_count_tag           2
#define AppPB_WorldClock_city_name_tag           3
#define AppPB_WorldClock_zone_offset_tag         4
#define AppPB_WorldClock_longitude_tag           5
#define AppPB_WorldClock_latitude_tag            6
#define AppPB_WorldClock_city_id_tag             7
#define AppPB_DisplayInfo_display_off_sec_tag    1
#define AppPB_DisplayInfo_backlight_tag          2
#define AppPB_DisplayInfo_last_brt_tag           3
#define AppPB_DisplayInfo_theme_screen_tag       4
#define AppPB_DisplayInfo_effect_style_tag       5
#define AppPB_DisplayInfo_interface_style_tag    6
#define AppPB_DisplayInfo_jump_home_tag          7
#define AppPB_DisplayInfo_dial_lock_tag          8
#define AppPB_AppBind_new_bind_uid_tag           1
#define AppPB_AppBind_save_bind_uid_tag          2
#define AppPB_AppBind_qr_random_tag              3
#define AppPB_AppBind_conn_before_tag            4
#define AppPB_AppBind_bind_notify_tag            5
#define AppPB_AppBind_our_app_conn_tag           6
#define AppPB_AppBind_bind_start_tag             7
#define AppPB_AppBind_disp_screen_tag            8
#define AppPB_AppBind_conn_sec_cnt_tag           9
#define AppPB_Power_power_save_tag               1
#define AppPB_Power_everbright_tag               2
#define AppPB_Power_hr_auto_tag                  3
#define AppPB_Power_spo2_auto_tag                4
#define AppPB_Power_pressure_auto_tag            5
#define AppPB_Power_emotion_auto_tag             6
#define AppPB_Power_theater_tag                  7
#define AppPB_Power_motion_reco_tag              8
#define AppPB_SleepSet_Schedule_day_of_week_tag  1
#define AppPB_SleepSet_Schedule_fall_hour_tag    2
#define AppPB_SleepSet_Schedule_fall_min_tag     3
#define AppPB_SleepSet_Schedule_wake_hour_tag    4
#define AppPB_SleepSet_Schedule_wake_min_tag     5
#define AppPB_SleepSet_Schedule_is_alarm_tag     6
#define AppPB_SleepSet_schedule_tag              1
#define AppPB_SleepSet_mode_switch_tag           2
#define AppPB_SleepSet_mode_status_tag           3
#define AppPB_SleepSet_target_dur_tag            4
#define AppPB_SleepSet_remind_switch_tag         5
#define AppPB_SleepSet_remind_tag                6
#define AppPB_SleepSet_snooze_on_tag             7
#define AppPB_SleepSet_snooze_time_tag           8
#define AppPB_SleepSet_snooze_cnt_tag            9
#define AppPB_WatchCfg_pixel_width_tag           1
#define AppPB_WatchCfg_pixel_height_tag          2
#define AppPB_WatchCfg_file_crc32_tag            3
#define AppPB_WatchCfg_cur_index_tag             4
#define AppPB_WatchCfg_aod_index_tag             5
#define AppPB_WatchCfg_sort_tag                  6

/* Struct field encoding specification for nanopb */
#define AppPB_DevInfo_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   model,             1) \
X(a, STATIC,   SINGULAR, STRING,   hw_ver,            2) \
X(a, STATIC,   SINGULAR, STRING,   sw_ver,            3) \
X(a, STATIC,   SINGULAR, STRING,   sn,                4) \
X(a, STATIC,   SINGULAR, STRING,   bt_addr,           5) \
X(a, STATIC,   SINGULAR, STRING,   pid,               6) \
X(a, STATIC,   SINGULAR, UINT64,   battery,           7)
#define AppPB_DevInfo_CALLBACK NULL
#define AppPB_DevInfo_DEFAULT NULL

#define AppPB_DevParam_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT64,   lang_id,           1) \
X(a, STATIC,   SINGULAR, UINT64,   zone,              2) \
X(a, STATIC,   SINGULAR, UINT64,   is_12h,            3) \
X(a, STATIC,   SINGULAR, UINT64,   is_mi,             4) \
X(a, STATIC,   SINGULAR, UINT64,   brt,               5)
#define AppPB_DevParam_CALLBACK NULL
#define AppPB_DevParam_DEFAULT NULL

#define AppPB_ElecCard_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     is_activate,       1) \
X(a, STATIC,   SINGULAR, BOOL,     is_reported,       2)
#define AppPB_ElecCard_CALLBACK NULL
#define AppPB_ElecCard_DEFAULT NULL

#define AppPB_Alarm_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT64,   index,             1) \
X(a, STATIC,   SINGULAR, UINT64,   repeat,            2) \
X(a, STATIC,   SINGULAR, UINT64,   on,                3) \
X(a, STATIC,   SINGULAR, UINT64,   hour,              4) \
X(a, STATIC,   SINGULAR, UINT64,   min,               5) \
X(a, STATIC,   SINGULAR, STRING,   name,              6)
#define AppPB_Alarm_CALLBACK NULL
#define AppPB_Alarm_DEFAULT NULL

#define AppPB_Weather_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, SINT64,   temp_cur,          1) \
X(a, STATIC,   SINGULAR, SINT64,   temp_max,          2) \
X(a, STATIC,   SINGULAR, SINT64,   temp_min,          3) \
X(a, STATIC,   SINGULAR, UINT64,   phen,              4) \
X(a, STATIC,   SINGULAR, UINT64,   humi,              5) \
X(a, STATIC,   SINGULAR, UINT64,   uv,                6) \
X(a, STATIC,   SINGULAR, SINT64,   pm25,              7) \
X(a, STATIC,   SINGULAR, SINT64,   aqi,               8) \
X(a, STATIC,   SINGULAR, STRING,   city,              9) \
X(a, STATIC,   REPEATED, MESSAGE,  day,              10)
#define AppPB_Weather_CALLBACK NULL
#define AppPB_Weather_DEFAULT NULL
#define AppPB_Weather_day_MSGTYPE AppPB_WeatherDay

#define AppPB_WeatherDay_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, SINT64,   temp_max,          1) \
X(a, STATIC,   SINGULAR, SINT64,   temp_min,          2) \
X(a, STATIC,   SINGULAR, UINT64,   phen,              3) \
X(a, STATIC,   SINGULAR, UINT64,   humi,              4)
#define AppPB_WeatherDay_CALLBACK NULL
#define AppPB_WeatherDay_DEFAULT NULL

#define AppPB_NotDisturb_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT64,   on,                1) \
X(a, STATIC,   SINGULAR, UINT64,   shour,             2) \
X(a, STATIC,   SINGULAR, UINT64,   smin,              3) \
X(a, STATIC,   SINGULAR, UINT64,   ehour,             4) \
X(a, STATIC,   SINGULAR, UINT64,   emin,              5) \
X(a, STATIC,   SINGULAR, UINT64,   repeat,            6)
#define AppPB_NotDisturb_CALLBACK NULL
#define AppPB_NotDisturb_DEFAULT NULL

#define AppPB_HeartRate_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT64,   is_auto,           1) \
X(a, STATIC,   SINGULAR, UINT64,   lwarn_on,          2) \
X(a, STATIC,   SINGULAR, UINT64,   hwarn_on,          3) \
X(a, STATIC,   SINGULAR, UINT64,   lwarn,             4) \
X(a, STATIC,   SINGULAR, UINT64,   hwarn,             5) \
X(a, STATIC,   SINGULAR, UINT64,   test_min,          6) \
X(a, STATIC,   SINGULAR, UINT64,   static_type,       7)
#define AppPB_HeartRate_CALLBACK NULL
#define AppPB_HeartRate_DEFAULT NULL

#define AppPB_Music_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   singer,            1) \
X(a, STATIC,   SINGULAR, STRING,   song_name,         2) \
X(a, STATIC,   SINGULAR, UINT64,   play_st,           3) \
X(a, STATIC,   SINGULAR, UINT64,   max_vol,           4) \
X(a, STATIC,   SINGULAR, UINT64,   cur_vol,           5) \
X(a, STATIC,   SINGULAR, UINT64,   app_st,            6)
#define AppPB_Music_CALLBACK NULL
#define AppPB_Music_DEFAULT NULL

#define AppPB_MsgInfo_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   app_name,          1) \
X(a, STATIC,   SINGULAR, STRING,   contact,           2) \
X(a, STATIC,   SINGULAR, STRING,   content,           3) \
X(a, STATIC,   SINGULAR, UINT64,   msg_id,            4) \
X(a, STATIC,   SINGULAR, STRING,   phone,             5) \
X(a, STATIC,   SINGULAR, UINT64,   msg_type,          6) \
X(a, STATIC,   SINGULAR, UINT64,   vibrate,           7)
#define AppPB_MsgInfo_CALLBACK NULL
#define AppPB_MsgInfo_DEFAULT NULL

#define AppPB_Contact_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   name,              1) \
X(a, STATIC,   SINGULAR, UINT64,   name_len,          2) \
X(a, STATIC,   SINGULAR, STRING,   phone,             3) \
X(a, STATIC,   SINGULAR, UINT64,   phone_len,         4) \
X(a, STATIC,   SINGULAR, UINT64,   state,             5)
#define AppPB_Contact_CALLBACK NULL
#define AppPB_Contact_DEFAULT NULL

#define AppPB_SportTgt_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT64,   motion_t,          1) \
X(a, STATIC,   SINGULAR, UINT64,   goal_type,         2) \
X(a, STATIC,   SINGULAR, UINT64,   step,              3) \
X(a, STATIC,   SINGULAR, UINT64,   kcal,              4) \
X(a, STATIC,   SINGULAR, UINT64,   meter,             5) \
X(a, STATIC,   SINGULAR, UINT64,   duration,          6)
#define AppPB_SportTgt_CALLBACK NULL
#define AppPB_SportTgt_DEFAULT NULL

#define AppPB_UserPhys_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT64,   age,               1) \
X(a, STATIC,   SINGULAR, UINT64,   birthday,          2) \
X(a, STATIC,   SINGULAR, UINT64,   gender,            3) \
X(a, STATIC,   SINGULAR, UINT64,   height,            4) \
X(a, STATIC,   SINGULAR, UINT64,   weight,            5) \
X(a, STATIC,   SINGULAR, UINT64,   vo2max,            6) \
X(a, STATIC,   SINGULAR, UINT64,   run_step,          7) \
X(a, STATIC,   SINGULAR, UINT64,   walk_step,         8)
#define AppPB_UserPhys_CALLBACK NULL
#define AppPB_UserPhys_DEFAULT NULL

#define AppPB_MotionSum_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT64,   hr_value,          1) \
X(a, STATIC,   SINGULAR, UINT64,   hr_ts,             2) \
X(a, STATIC,   SINGULAR, UINT64,   kcal,              3) \
X(a, STATIC,   SINGULAR, UINT64,   distance,          4) \
X(a, STATIC,   SINGULAR, UINT64,   elevation,         5) \
X(a, STATIC,   SINGULAR, UINT64,   sleep_time,        6) \
X(a, STATIC,   SINGULAR, UINT64,   step,              7)
#define AppPB_MotionSum_CALLBACK NULL
#define AppPB_MotionSum_DEFAULT NULL

#define AppPB_SportState_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT64,   monitor_st,        1) \
X(a, STATIC,   SINGULAR, UINT64,   operator_t,        2) \
X(a, STATIC,   SINGULAR, UINT64,   sport_type,        3) \
X(a, STATIC,   SINGULAR, UINT64,   start_time,        4) \
X(a, STATIC,   SINGULAR, UINT64,   workout_type,      5) \
X(a, STATIC,   SINGULAR, UINT64,   op_time,           6)
#define AppPB_SportState_CALLBACK NULL
#define AppPB_SportState_DEFAULT NULL

#define AppPB_Position_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT64,   speed,             1) \
X(a, STATIC,   SINGULAR, UINT64,   distance,          2) \
X(a, STATIC,   SINGULAR, SINT64,   altitude,          3) \
X(a, STATIC,   SINGULAR, UINT64,   total_dist,        4) \
X(a, STATIC,   SINGULAR, UINT64,   start_time,        5) \
X(a, STATIC,   SINGULAR, UINT64,   end_time,          6) \
X(a, STATIC,   SINGULAR, SINT64,   latitude,          7) \
X(a, STATIC,   SINGULAR, SINT64,   longitude,         8) \
X(a, STATIC,   SINGULAR, UINT64,   bearing,           9) \
X(a, STATIC,   SINGULAR, UINT64,   accuracy,         10)
#define AppPB_Position_CALLBACK NULL
#define AppPB_Position_DEFAULT NULL

#define AppPB_FemCycle_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT64,   remind_sw,         1) \
X(a, STATIC,   SINGULAR, UINT64,   menstr_remind,     2) \
X(a, STATIC,   SINGULAR, UINT64,   menstr_end_remind,   3) \
X(a, STATIC,   SINGULAR, UINT64,   ovulat_remind,     4) \
X(a, STATIC,   SINGULAR, UINT64,   ovulat_end_remind,   5) \
X(a, STATIC,   SINGULAR, UINT64,   cycle_start,       6) \
X(a, STATIC,   SINGULAR, UINT64,   cycle_end,         7) \
X(a, STATIC,   SINGULAR, UINT64,   keep_days,         8) \
X(a, STATIC,   SINGULAR, UINT64,   cycle_days,        9)
#define AppPB_FemCycle_CALLBACK NULL
#define AppPB_FemCycle_DEFAULT NULL

#define AppPB_Account_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   account,           1) \
X(a, STATIC,   SINGULAR, UINT64,   acc_len,           2) \
X(a, STATIC,   SINGULAR, UINT64,   pair_state,        3) \
X(a, STATIC,   SINGULAR, UINT64,   app_role,          4)
#define AppPB_Account_CALLBACK NULL
#define AppPB_Account_DEFAULT NULL

#define AppPB_SportMng_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT64,   max_add_num,       1) \
X(a, STATIC,   SINGULAR, UINT64,   min_add_num,       2) \
X(a, STATIC,   REPEATED, UINT64,   sport_type,        3)
#define AppPB_SportMng_CALLBACK NULL
#define AppPB_SportMng_DEFAULT NULL

#define AppPB_SportRcd_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT64,   id,                1) \
X(a, STATIC,   SINGULAR, UINT64,   status,            2) \
X(a, STATIC,   SINGULAR, UINT64,   start_time,        3) \
X(a, STATIC,   SINGULAR, UINT64,   end_time,          4) \
X(a, STATIC,   SINGULAR, UINT64,   calorie,           5) \
X(a, STATIC,   SINGULAR, UINT64,   distance,          6) \
X(a, STATIC,   SINGULAR, UINT64,   step,              7) \
X(a, STATIC,   SINGULAR, UINT64,   duration,          8) \
X(a, STATIC,   SINGULAR, UINT64,   speed,             9) \
X(a, STATIC,   SINGULAR, UINT64,   type,             10)
#define AppPB_SportRcd_CALLBACK NULL
#define AppPB_SportRcd_DEFAULT NULL

#define AppPB_SysClock_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT64,   year,              1) \
X(a, STATIC,   SINGULAR, UINT64,   month,             2) \
X(a, STATIC,   SINGULAR, UINT64,   day,               3) \
X(a, STATIC,   SINGULAR, UINT64,   hour,              4) \
X(a, STATIC,   SINGULAR, UINT64,   minute,            5) \
X(a, STATIC,   SINGULAR, UINT64,   second,            6) \
X(a, STATIC,   SINGULAR, SINT64,   zone,              7) \
X(a, STATIC,   SINGULAR, UENUM,    mode,              8)
#define AppPB_SysClock_CALLBACK NULL
#define AppPB_SysClock_DEFAULT NULL

#define AppPB_WorldClock_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   now_index,         1) \
X(a, STATIC,   SINGULAR, UINT32,   max_count,         2) \
X(a, STATIC,   SINGULAR, STRING,   city_name,         3) \
X(a, STATIC,   SINGULAR, SINT64,   zone_offset,       4) \
X(a, STATIC,   SINGULAR, DOUBLE,   longitude,         5) \
X(a, STATIC,   SINGULAR, DOUBLE,   latitude,          6) \
X(a, STATIC,   SINGULAR, UINT32,   city_id,           7)
#define AppPB_WorldClock_CALLBACK NULL
#define AppPB_WorldClock_DEFAULT NULL

#define AppPB_DisplayInfo_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT64,   display_off_sec,   1) \
X(a, STATIC,   SINGULAR, UINT64,   backlight,         2) \
X(a, STATIC,   SINGULAR, UINT64,   last_brt,          3) \
X(a, STATIC,   SINGULAR, UINT64,   theme_screen,      4) \
X(a, STATIC,   SINGULAR, UINT64,   effect_style,      5) \
X(a, STATIC,   SINGULAR, UINT64,   interface_style,   6) \
X(a, STATIC,   SINGULAR, UINT64,   jump_home,         7) \
X(a, STATIC,   SINGULAR, UINT64,   dial_lock,         8)
#define AppPB_DisplayInfo_CALLBACK NULL
#define AppPB_DisplayInfo_DEFAULT NULL

#define AppPB_AppBind_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT64,   new_bind_uid,      1) \
X(a, STATIC,   SINGULAR, UINT64,   save_bind_uid,     2) \
X(a, STATIC,   SINGULAR, UINT64,   qr_random,         3) \
X(a, STATIC,   SINGULAR, UINT64,   conn_before,       4) \
X(a, STATIC,   SINGULAR, UINT64,   bind_notify,       5) \
X(a, STATIC,   SINGULAR, UINT64,   our_app_conn,      6) \
X(a, STATIC,   SINGULAR, UINT64,   bind_start,        7) \
X(a, STATIC,   SINGULAR, UINT64,   disp_screen,       8) \
X(a, STATIC,   SINGULAR, UINT64,   conn_sec_cnt,      9)
#define AppPB_AppBind_CALLBACK NULL
#define AppPB_AppBind_DEFAULT NULL

#define AppPB_Power_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT64,   power_save,        1) \
X(a, STATIC,   SINGULAR, UINT64,   everbright,        2) \
X(a, STATIC,   SINGULAR, UINT64,   hr_auto,           3) \
X(a, STATIC,   SINGULAR, UINT64,   spo2_auto,         4) \
X(a, STATIC,   SINGULAR, UINT64,   pressure_auto,     5) \
X(a, STATIC,   SINGULAR, UINT64,   emotion_auto,      6) \
X(a, STATIC,   SINGULAR, UINT64,   theater,           7) \
X(a, STATIC,   SINGULAR, UINT64,   motion_reco,       8)
#define AppPB_Power_CALLBACK NULL
#define AppPB_Power_DEFAULT NULL

#define AppPB_SleepSet_FIELDLIST(X, a) \
X(a, STATIC,   REPEATED, MESSAGE,  schedule,          1) \
X(a, STATIC,   SINGULAR, UINT64,   mode_switch,       2) \
X(a, STATIC,   SINGULAR, UINT64,   mode_status,       3) \
X(a, STATIC,   SINGULAR, UINT64,   target_dur,        4) \
X(a, STATIC,   SINGULAR, UINT64,   remind_switch,     5) \
X(a, STATIC,   SINGULAR, UINT64,   remind,            6) \
X(a, STATIC,   SINGULAR, UINT64,   snooze_on,         7) \
X(a, STATIC,   SINGULAR, UINT64,   snooze_time,       8) \
X(a, STATIC,   SINGULAR, UINT64,   snooze_cnt,        9)
#define AppPB_SleepSet_CALLBACK NULL
#define AppPB_SleepSet_DEFAULT NULL
#define AppPB_SleepSet_schedule_MSGTYPE AppPB_SleepSet_Schedule

#define AppPB_SleepSet_Schedule_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT64,   day_of_week,       1) \
X(a, STATIC,   SINGULAR, UINT64,   fall_hour,         2) \
X(a, STATIC,   SINGULAR, UINT64,   fall_min,          3) \
X(a, STATIC,   SINGULAR, UINT64,   wake_hour,         4) \
X(a, STATIC,   SINGULAR, UINT64,   wake_min,          5) \
X(a, STATIC,   SINGULAR, UINT64,   is_alarm,          6)
#define AppPB_SleepSet_Schedule_CALLBACK NULL
#define AppPB_SleepSet_Schedule_DEFAULT NULL

#define AppPB_WatchCfg_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT64,   pixel_width,       1) \
X(a, STATIC,   SINGULAR, UINT64,   pixel_height,      2) \
X(a, STATIC,   SINGULAR, UINT64,   file_crc32,        3) \
X(a, STATIC,   SINGULAR, UINT64,   cur_index,         4) \
X(a, STATIC,   SINGULAR, UINT64,   aod_index,         5) \
X(a, STATIC,   REPEATED, UINT64,   sort,              6)
#define AppPB_WatchCfg_CALLBACK NULL
#define AppPB_WatchCfg_DEFAULT NULL

extern const pb_msgdesc_t AppPB_DevInfo_msg;
extern const pb_msgdesc_t AppPB_DevParam_msg;
extern const pb_msgdesc_t AppPB_ElecCard_msg;
extern const pb_msgdesc_t AppPB_Alarm_msg;
extern const pb_msgdesc_t AppPB_Weather_msg;
extern const pb_msgdesc_t AppPB_WeatherDay_msg;
extern const pb_msgdesc_t AppPB_NotDisturb_msg;
extern const pb_msgdesc_t AppPB_HeartRate_msg;
extern const pb_msgdesc_t AppPB_Music_msg;
extern const pb_msgdesc_t AppPB_MsgInfo_msg;
extern const pb_msgdesc_t AppPB_Contact_msg;
extern const pb_msgdesc_t AppPB_SportTgt_msg;
extern const pb_msgdesc_t AppPB_UserPhys_msg;
extern const pb_msgdesc_t AppPB_MotionSum_msg;
extern const pb_msgdesc_t AppPB_SportState_msg;
extern const pb_msgdesc_t AppPB_Position_msg;
extern const pb_msgdesc_t AppPB_FemCycle_msg;
extern const pb_msgdesc_t AppPB_Account_msg;
extern const pb_msgdesc_t AppPB_SportMng_msg;
extern const pb_msgdesc_t AppPB_SportRcd_msg;
extern const pb_msgdesc_t AppPB_SysClock_msg;
extern const pb_msgdesc_t AppPB_WorldClock_msg;
extern const pb_msgdesc_t AppPB_DisplayInfo_msg;
extern const pb_msgdesc_t AppPB_AppBind_msg;
extern const pb_msgdesc_t AppPB_Power_msg;
extern const pb_msgdesc_t AppPB_SleepSet_msg;
extern const pb_msgdesc_t AppPB_SleepSet_Schedule_msg;
extern const pb_msgdesc_t AppPB_WatchCfg_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define AppPB_DevInfo_fields &AppPB_DevInfo_msg
#define AppPB_DevParam_fields &AppPB_DevParam_msg
#define AppPB_ElecCard_fields &AppPB_ElecCard_msg
#define AppPB_Alarm_fields &AppPB_Alarm_msg
#define AppPB_Weather_fields &AppPB_Weather_msg
#define AppPB_WeatherDay_fields &AppPB_WeatherDay_msg
#define AppPB_NotDisturb_fields &AppPB_NotDisturb_msg
#define AppPB_HeartRate_fields &AppPB_HeartRate_msg
#define AppPB_Music_fields &AppPB_Music_msg
#define AppPB_MsgInfo_fields &AppPB_MsgInfo_msg
#define AppPB_Contact_fields &AppPB_Contact_msg
#define AppPB_SportTgt_fields &AppPB_SportTgt_msg
#define AppPB_UserPhys_fields &AppPB_UserPhys_msg
#define AppPB_MotionSum_fields &AppPB_MotionSum_msg
#define AppPB_SportState_fields &AppPB_SportState_msg
#define AppPB_Position_fields &AppPB_Position_msg
#define AppPB_FemCycle_fields &AppPB_FemCycle_msg
#define AppPB_Account_fields &AppPB_Account_msg
#define AppPB_SportMng_fields &AppPB_SportMng_msg
#define AppPB_SportRcd_fields &AppPB_SportRcd_msg
#define AppPB_SysClock_fields &AppPB_SysClock_msg
#define AppPB_WorldClock_fields &AppPB_WorldClock_msg
#define AppPB_DisplayInfo_fields &AppPB_DisplayInfo_msg
#define AppPB_AppBind_fields &AppPB_AppBind_msg
#define AppPB_Power_fields &AppPB_Power_msg
#define AppPB_SleepSet_fields &AppPB_SleepSet_msg
#define AppPB_SleepSet_Schedule_fields &AppPB_SleepSet_Schedule_msg
#define AppPB_WatchCfg_fields &AppPB_WatchCfg_msg

/* Maximum encoded size of messages (where known) */
#define AppPB_Account_size                       266
#define AppPB_Alarm_size                         145
#define AppPB_AppBind_size                       36
#define AppPB_Contact_size                       174
#define AppPB_DevInfo_size                       137
#define AppPB_DevParam_size                      18
#define AppPB_DisplayInfo_size                   24
#define AppPB_ElecCard_size                      4
#define AppPB_FemCycle_size                      34
#define AppPB_HeartRate_size                     22
#define AppPB_MotionSum_size                     39
#define AppPB_MsgInfo_size                       302
#define AppPB_Music_size                         142
#define AppPB_NotDisturb_size                    18
#define AppPB_Position_size                      49
#define AppPB_Power_size                         24
#define AppPB_SleepSet_Schedule_size             18
#define AppPB_SleepSet_size                      169
#define AppPB_SportMng_size                      358
#define AppPB_SportRcd_size                      50
#define AppPB_SportState_size                    24
#define AppPB_SportTgt_size                      30
#define AppPB_SysClock_size                      27
#define AppPB_UserPhys_size                      42
#define AppPB_WatchCfg_size                      108
#define AppPB_WeatherDay_size                    14
#define AppPB_Weather_size                       206
#define AppPB_WorldClock_size                    137

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
