/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.7 */

#ifndef PB_APP_NANOPB_AUX_PB_H_INCLUDED
#define PB_APP_NANOPB_AUX_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
/* 错误码(错误类型) */
typedef enum _AppPB_ACK_Code {
    AppPB_ACK_Code_SUCCEED = 0, /* 应答成功 */
    AppPB_ACK_Code_CRC_FAILED = 1, /* CRC校验失败 */
    AppPB_ACK_Code_CHK_FAILED = 2, /* CheckSum校验失败 */
    AppPB_ACK_Code_PKG_INVALID = 3 /* 分包无效(包错误) */
} AppPB_ACK_Code;

/* 子类型 */
typedef enum _AppPB_ACK_Type {
    AppPB_ACK_Type_MINI_MSG = 0, /* 小消息 */
    AppPB_ACK_Type_FILE_MSG = 1 /* 文件消息 */
} AppPB_ACK_Type;

/* 关键消息(请求语义) */
typedef enum _AppPB_ACK_Info {
    AppPB_ACK_Info_NO_QUESTION = 0, /* 无疑问 */
    AppPB_ACK_Info_REQUEST_REPEAT = 1 /* 要求重发 */
} AppPB_ACK_Info;

/* 请求读取的文件类型 */
typedef enum _AppPB_Sync_Type {
    AppPB_Sync_Type_SYNC_FT_NONE = 0, /* 不读文件,读普通消息 */
    AppPB_Sync_Type_SYNC_FT_LOG = 1, /* 日志文件 */
    AppPB_Sync_Type_SYNC_FT_FW = 2, /* 固件文件 */
    AppPB_Sync_Type_SYNC_FT_CWF = 3, /* 云表盘文件 */
    AppPB_Sync_Type_SYNC_FT_SWF = 4 /* 息屏表盘文件 */
} AppPB_Sync_Type;

/* Struct definitions */
/* 辅助应答消息 */
typedef struct _AppPB_ACK {
    AppPB_ACK_Code code; /* 应答错误码 */
    AppPB_ACK_Type type; /* 应答类别 */
    AppPB_ACK_Info info; /* 关键消息 */
    /* message编码: */
    uint16_t msg;
} AppPB_ACK;

/* 辅助同步消息(读请求) */
typedef struct _AppPB_Sync {
    AppPB_Sync_Type type;
    /* message编码: */
    uint16_t msg;
} AppPB_Sync;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _AppPB_ACK_Code_MIN AppPB_ACK_Code_SUCCEED
#define _AppPB_ACK_Code_MAX AppPB_ACK_Code_PKG_INVALID
#define _AppPB_ACK_Code_ARRAYSIZE ((AppPB_ACK_Code)(AppPB_ACK_Code_PKG_INVALID+1))

#define _AppPB_ACK_Type_MIN AppPB_ACK_Type_MINI_MSG
#define _AppPB_ACK_Type_MAX AppPB_ACK_Type_FILE_MSG
#define _AppPB_ACK_Type_ARRAYSIZE ((AppPB_ACK_Type)(AppPB_ACK_Type_FILE_MSG+1))

#define _AppPB_ACK_Info_MIN AppPB_ACK_Info_NO_QUESTION
#define _AppPB_ACK_Info_MAX AppPB_ACK_Info_REQUEST_REPEAT
#define _AppPB_ACK_Info_ARRAYSIZE ((AppPB_ACK_Info)(AppPB_ACK_Info_REQUEST_REPEAT+1))

#define _AppPB_Sync_Type_MIN AppPB_Sync_Type_SYNC_FT_NONE
#define _AppPB_Sync_Type_MAX AppPB_Sync_Type_SYNC_FT_SWF
#define _AppPB_Sync_Type_ARRAYSIZE ((AppPB_Sync_Type)(AppPB_Sync_Type_SYNC_FT_SWF+1))

#define AppPB_ACK_code_ENUMTYPE AppPB_ACK_Code
#define AppPB_ACK_type_ENUMTYPE AppPB_ACK_Type
#define AppPB_ACK_info_ENUMTYPE AppPB_ACK_Info

#define AppPB_Sync_type_ENUMTYPE AppPB_Sync_Type


/* Initializer values for message structs */
#define AppPB_ACK_init_default                   {_AppPB_ACK_Code_MIN, _AppPB_ACK_Type_MIN, _AppPB_ACK_Info_MIN, 0}
#define AppPB_Sync_init_default                  {_AppPB_Sync_Type_MIN, 0}
#define AppPB_ACK_init_zero                      {_AppPB_ACK_Code_MIN, _AppPB_ACK_Type_MIN, _AppPB_ACK_Info_MIN, 0}
#define AppPB_Sync_init_zero                     {_AppPB_Sync_Type_MIN, 0}

/* Field tags (for use in manual encoding/decoding) */
#define AppPB_ACK_code_tag                       1
#define AppPB_ACK_type_tag                       2
#define AppPB_ACK_info_tag                       3
#define AppPB_ACK_msg_tag                        4
#define AppPB_Sync_type_tag                      1
#define AppPB_Sync_msg_tag                       2

/* Struct field encoding specification for nanopb */
#define AppPB_ACK_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    code,              1) \
X(a, STATIC,   SINGULAR, UENUM,    type,              2) \
X(a, STATIC,   SINGULAR, UENUM,    info,              3) \
X(a, STATIC,   SINGULAR, UINT32,   msg,               4)
#define AppPB_ACK_CALLBACK NULL
#define AppPB_ACK_DEFAULT NULL

#define AppPB_Sync_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    type,              1) \
X(a, STATIC,   SINGULAR, UINT32,   msg,               2)
#define AppPB_Sync_CALLBACK NULL
#define AppPB_Sync_DEFAULT NULL

extern const pb_msgdesc_t AppPB_ACK_msg;
extern const pb_msgdesc_t AppPB_Sync_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define AppPB_ACK_fields &AppPB_ACK_msg
#define AppPB_Sync_fields &AppPB_Sync_msg

/* Maximum encoded size of messages (where known) */
#define AppPB_ACK_size                           10
#define AppPB_Sync_size                          6

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
