/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.7 */

#include "app_nanopb_sys.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(AppPB_DevInfo, AppPB_DevInfo, AUTO)


PB_BIND(AppPB_DevParam, AppPB_DevParam, AUTO)


PB_BIND(AppPB_ElecCard, AppPB_ElecCard, AUTO)



