/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.7 */

#ifndef PB_APP_NANOPB_SYS_PB_H_INCLUDED
#define PB_APP_NANOPB_SYS_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
/* 设备信息消息(UTE 0xA4) */
typedef struct _AppPB_DevInfo {
    char model[16]; /* 设备型号 */
    char hw_ver[16]; /* 硬件版本 */
    char sw_ver[16]; /* 软件版本 */
    char sn[32]; /* 序列号 */
    char bt_addr[32]; /* 蓝牙地址 */
    char pid[16]; /* 产品ID */
    uint8_t battery; /* 电量 */
} AppPB_DevInfo;

/* 设备参数消息(UTE 0xA5) */
typedef struct _AppPB_DevParam {
    uint8_t lang_id; /* 语言ID */
    uint32_t zone; /* 时区 */
    uint8_t is_12h; /* 12/24小时制 */
    uint8_t is_mi; /* 距离单位(英里) */
    uint8_t brt; /* 屏幕亮度 */
} AppPB_DevParam;

/* 电子保卡消息(UTE 0xA2) */
typedef struct _AppPB_ElecCard {
    bool is_activate; /* 是否已激活 */
    bool is_reported; /* 是否已上报 */
} AppPB_ElecCard;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define AppPB_DevInfo_init_default               {"", "", "", "", "", "", 0}
#define AppPB_DevParam_init_default              {0, 0, 0, 0, 0}
#define AppPB_ElecCard_init_default              {0, 0}
#define AppPB_DevInfo_init_zero                  {"", "", "", "", "", "", 0}
#define AppPB_DevParam_init_zero                 {0, 0, 0, 0, 0}
#define AppPB_ElecCard_init_zero                 {0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define AppPB_DevInfo_model_tag                  1
#define AppPB_DevInfo_hw_ver_tag                 2
#define AppPB_DevInfo_sw_ver_tag                 3
#define AppPB_DevInfo_sn_tag                     4
#define AppPB_DevInfo_bt_addr_tag                5
#define AppPB_DevInfo_pid_tag                    6
#define AppPB_DevInfo_battery_tag                7
#define AppPB_DevParam_lang_id_tag               1
#define AppPB_DevParam_zone_tag                  2
#define AppPB_DevParam_is_12h_tag                3
#define AppPB_DevParam_is_mi_tag                 4
#define AppPB_DevParam_brt_tag                   5
#define AppPB_ElecCard_is_activate_tag           1
#define AppPB_ElecCard_is_reported_tag           2

/* Struct field encoding specification for nanopb */
#define AppPB_DevInfo_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   model,             1) \
X(a, STATIC,   SINGULAR, STRING,   hw_ver,            2) \
X(a, STATIC,   SINGULAR, STRING,   sw_ver,            3) \
X(a, STATIC,   SINGULAR, STRING,   sn,                4) \
X(a, STATIC,   SINGULAR, STRING,   bt_addr,           5) \
X(a, STATIC,   SINGULAR, STRING,   pid,               6) \
X(a, STATIC,   SINGULAR, UINT64,   battery,           7)
#define AppPB_DevInfo_CALLBACK NULL
#define AppPB_DevInfo_DEFAULT NULL

#define AppPB_DevParam_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT64,   lang_id,           1) \
X(a, STATIC,   SINGULAR, UINT64,   zone,              2) \
X(a, STATIC,   SINGULAR, UINT64,   is_12h,            3) \
X(a, STATIC,   SINGULAR, UINT64,   is_mi,             4) \
X(a, STATIC,   SINGULAR, UINT64,   brt,               5)
#define AppPB_DevParam_CALLBACK NULL
#define AppPB_DevParam_DEFAULT NULL

#define AppPB_ElecCard_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     is_activate,       1) \
X(a, STATIC,   SINGULAR, BOOL,     is_reported,       2)
#define AppPB_ElecCard_CALLBACK NULL
#define AppPB_ElecCard_DEFAULT NULL

extern const pb_msgdesc_t AppPB_DevInfo_msg;
extern const pb_msgdesc_t AppPB_DevParam_msg;
extern const pb_msgdesc_t AppPB_ElecCard_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define AppPB_DevInfo_fields &AppPB_DevInfo_msg
#define AppPB_DevParam_fields &AppPB_DevParam_msg
#define AppPB_ElecCard_fields &AppPB_ElecCard_msg

/* Maximum encoded size of messages (where known) */
#define AppPB_DevInfo_size                       137
#define AppPB_DevParam_size                      18
#define AppPB_ElecCard_size                      4

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
