/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.7 */

#include "app_nanopb_func.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(AppPB_DevInfo, AppPB_DevInfo, AUTO)


PB_BIND(AppPB_DevParam, AppPB_DevParam, AUTO)


PB_BIND(AppPB_ElecCard, AppPB_ElecCard, AUTO)


PB_BIND(AppPB_Alarm, AppPB_Alarm, AUTO)


PB_BIND(AppPB_Weather, AppPB_Weather, AUTO)


PB_BIND(AppPB_WeatherDay, AppPB_WeatherDay, AUTO)


PB_BIND(AppPB_NotDisturb, AppPB_NotDisturb, AUTO)


PB_BIND(AppPB_HeartRate, AppPB_HeartRate, AUTO)


PB_BIND(AppPB_Music, AppPB_Music, AUTO)


PB_BIND(AppPB_MsgInfo, AppPB_MsgInfo, 2)


PB_BIND(AppPB_Contact, AppPB_Contact, AUTO)


PB_BIND(AppPB_SportTgt, AppPB_SportTgt, AUTO)


PB_BIND(AppPB_UserPhys, AppPB_UserPhys, AUTO)


PB_BIND(AppPB_MotionSum, AppPB_MotionSum, AUTO)


PB_BIND(AppPB_SportState, AppPB_SportState, AUTO)


PB_BIND(AppPB_Position, AppPB_Position, AUTO)


PB_BIND(AppPB_FemCycle, AppPB_FemCycle, AUTO)


PB_BIND(AppPB_Account, AppPB_Account, 2)


PB_BIND(AppPB_SportMng, AppPB_SportMng, 2)


PB_BIND(AppPB_SportRcd, AppPB_SportRcd, AUTO)


PB_BIND(AppPB_SysClock, AppPB_SysClock, AUTO)


PB_BIND(AppPB_WorldClock, AppPB_WorldClock, AUTO)


PB_BIND(AppPB_DisplayInfo, AppPB_DisplayInfo, AUTO)


PB_BIND(AppPB_AppBind, AppPB_AppBind, AUTO)


PB_BIND(AppPB_Power, AppPB_Power, AUTO)


PB_BIND(AppPB_SleepSet, AppPB_SleepSet, AUTO)


PB_BIND(AppPB_SleepSet_Schedule, AppPB_SleepSet_Schedule, AUTO)


PB_BIND(AppPB_WatchCfg, AppPB_WatchCfg, AUTO)




#ifndef PB_CONVERT_DOUBLE_FLOAT
/* On some platforms (such as AVR), double is really float.
 * To be able to encode/decode double on these platforms, you need.
 * to define PB_CONVERT_DOUBLE_FLOAT in pb.h or compiler command line.
 */
PB_STATIC_ASSERT(sizeof(double) == 8, DOUBLE_MUST_BE_8_BYTES)
#endif

