syntax = "proto3";
option optimize_for = LITE_RUNTIME;
/* Java包字段:Java编译时使用 */
option java_package = "com.message_sys.nanopb";
option java_outer_classname = "AppPB_MsgSysProto";
/* 依赖包 */
import "nanopb.proto";

/* 设备信息消息(UTE 0xA4) */
message AppPB_DevInfo {
    string  model   = 1 [(nanopb).max_size = 16];   //设备型号
    string  hw_ver  = 2 [(nanopb).max_size = 16];   //硬件版本
    string  sw_ver  = 3 [(nanopb).max_size = 16];   //软件版本
    string  sn      = 4 [(nanopb).max_size = 32];   //序列号
    string  bt_addr = 5 [(nanopb).max_size = 32];   //蓝牙地址
    string  pid     = 6 [(nanopb).max_size = 16];   //产品ID
    uint64  battery = 7 [(nanopb).int_size = IS_8]; //电量
}

/* 设备参数消息(UTE 0xA5) */
message AppPB_DevParam {
    uint64  lang_id = 1 [(nanopb).int_size = IS_8];  //语言ID
    uint64  zone    = 2 [(nanopb).int_size = IS_32]; //时区
    uint64  is_12h  = 3 [(nanopb).int_size = IS_8];  //12/24小时制
    uint64  is_mi   = 4 [(nanopb).int_size = IS_8];  //距离单位(英里)
    uint64  brt     = 5 [(nanopb).int_size = IS_8];  //屏幕亮度
}

/* 电子保卡消息(UTE 0xA2) */
message AppPB_ElecCard {
    bool  is_activate = 1;   //是否已激活
    bool  is_reported = 2;   //是否已上报
}
