syntax = "proto3";
option optimize_for = LITE_RUNTIME;
option java_package = "com.message_aux.nanopb";
option java_outer_classname = "AppPB_MsgFileAux";
import "nanopb.proto";

/* 辅助应答消息 */
message AppPB_ACK {
    /* 错误码(错误类型) */
    enum Code {
        SUCCEED     = 0x00;     //应答成功
        CRC_FAILED  = 0x01;     //CRC校验失败
        CHK_FAILED  = 0x02;     //CheckSum校验失败
        PKG_INVALID = 0x03;     //分包无效(包错误)
    }
    /* 子类型 */
    enum Type {
        MINI_MSG = 0x00;        //小消息
        FILE_MSG = 0x01;        //文件消息
    }
    /* 关键消息(请求语义) */
    enum Info {
        NO_QUESTION    = 0x00;     //无疑问
        REQUEST_REPEAT = 0x01;     //要求重发
    }

    Code code = 1;  //应答错误码
    Type type = 2;  //应答类别
    Info info = 3;  //关键消息
    
    /* message编码: */
    uint32 msg = 4 [(nanopb).int_size = IS_16];
}

/* 辅助同步消息(读请求) */
message AppPB_Sync {
    /* 请求读取的文件类型 */
    enum Type {
        SYNC_FT_NONE = 0;    //不读文件,读普通消息
        SYNC_FT_LOG  = 1;    //日志文件
        SYNC_FT_FW   = 2;    //固件文件
        SYNC_FT_CWF  = 3;    //云表盘文件
        SYNC_FT_SWF  = 4;    //息屏表盘文件
    }
    Type type = 1;
    
    /* message编码: */
    uint32 msg = 2 [(nanopb).int_size = IS_16];
}