/*
 * Autogenerated by the Meson build system.
 * Do not edit, your changes will be lost.
 */

#ifndef TVG_CONFIG_H
#define TVG_CONFIG_H

#include "scui_draw_thorvg.h"

#define THORVG_SW_RASTER_SUPPORT 1

#define THORVG_SVG_LOADER_SUPPORT SCUI_USE_LOTTIE

#define THORVG_LOTTIE_LOADER_SUPPORT SCUI_USE_LOTTIE

#define THORVG_VERSION_STRING "0.15.3"

#if SCUI_DRAW_SW_DRAW_UNIT_CNT > 1
#define THORVG_THREAD_SUPPORT
#endif


#endif /*TVG_CONFIG_H*/
