#ifndef SCUI_LOG_H
#define SCUI_LOG_H

/* 转为适配app_sys_log接口
 */

#ifdef  SCUI_LOG_LOCAL_STATUS
#ifdef  APP_SYS_LOG_LOCAL_STATUS
#undef  APP_SYS_LOG_LOCAL_STATUS
#endif
#define APP_SYS_LOG_LOCAL_STATUS SCUI_LOG_LOCAL_STATUS
#endif

#ifdef  SCUI_LOG_LOCAL_LEVEL
#ifdef  APP_SYS_LOG_LOCAL_LEVEL
#undef  APP_SYS_LOG_LOCAL_LEVEL
#endif
#define APP_SYS_LOG_LOCAL_LEVEL  SCUI_LOG_LOCAL_LEVEL
#endif

#define SCUI_LOG_DEBUG      APP_SYS_LOG_DEBUG
#define SCUI_LOG_DEBUG_RAW  APP_SYS_LOG_DEBUG_RAW
#define SCUI_LOG_INFO       APP_SYS_LOG_INFO
#define SCUI_LOG_INFO_RAW   APP_SYS_LOG_INFO_RAW
#define SCUI_LOG_WARN       APP_SYS_LOG_WARN
#define SCUI_LOG_WARN_RAW   APP_SYS_LOG_WARN_RAW
#define SCUI_LOG_ERROR      APP_SYS_LOG_ERROR
#define SCUI_LOG_ERROR_RAW  APP_SYS_LOG_ERROR_RAW
#define SCUI_LOG_LINE       app_sys_log_line()
#define SCUI_ASSERT         APP_SYS_ASSERT

#endif
