#ifndef SCUI_WIDGET_PARSER_H
#define SCUI_WIDGET_PARSER_H

/*一个通过scui_widget_parser脚本生成的widget表
 */

typedef enum {
	SCUI_HANDLE_OFFSET_WIDGET = 0x1000 - 1,
	SCUI_UI_SCENE_BUTTERFLY, // 4096, 0x1000
	SCUI_UI_SCENE_BUTTERFLY_CUSTOM, // 4097, 0x1001
	SCUI_UI_SCENE_CUBE, // 4098, 0x1002
	SCUI_UI_SCENE_CUBE_CUSTOM, // 4099, 0x1003
	SCUI_UI_SCENE_LANTERN, // 4100, 0x1004
	SCUI_UI_SCENE_LANTERN_CUSTOM, // 4101, 0x1005
	SCUI_UI_SCENE_SOCCER, // 4102, 0x1006
	SCUI_UI_SCENE_SOCCER_CUSTOM, // 4103, 0x1007
	SCUI_UI_SCENE_ACTIVITY, // 4104, 0x1008
	SCUI_UI_SCENE_ACTIVITY_SCROLL, // 4105, 0x1009
	SCUI_UI_SCENE_ACTIVITY_BAR_ARC, // 4106, 0x100a
	SCUI_UI_SCENE_ACTIVITY_SCROLL_RING_BIG_3, // 4107, 0x100b
	SCUI_UI_SCENE_ACTIVITY_SCROLL_DITAIL_TITLE, // 4108, 0x100c
	SCUI_UI_SCENE_ACTIVITY_SCROLL_DITAIL_SUM, // 4109, 0x100d
	SCUI_UI_SCENE_ACTIVITY_SCROLL_DITAIL_KCAL, // 4110, 0x100e
	SCUI_UI_SCENE_ACTIVITY_SCROLL_DITAIL_STEP, // 4111, 0x100f
	SCUI_UI_SCENE_ACTIVITY_SCROLL_DITAIL_DIST, // 4112, 0x1010
	SCUI_UI_SCENE_ACTIVITY_SCROLL_BLANK, // 4113, 0x1011
	SCUI_UI_SCENE_HOME, // 4114, 0x1012
	SCUI_UI_SCENE_HR, // 4115, 0x1013
	SCUI_UI_SCENE_HR_BODY, // 4116, 0x1014
	SCUI_UI_SCENE_HR_TITLE, // 4117, 0x1015
	SCUI_UI_SCENE_HR_VALUE, // 4118, 0x1016
	SCUI_UI_SCENE_HR_UNIT, // 4119, 0x1017
	SCUI_UI_SCENE_HR_TIME, // 4120, 0x1018
	SCUI_UI_SCENE_HR_BTN_TEXT, // 4121, 0x1019
	SCUI_UI_SCENE_MINI_CARD, // 4122, 0x101a
	SCUI_UI_SCENE_MINI_CARD_BAR_ARC, // 4123, 0x101b
	SCUI_UI_SCENE_MINI_CARD_MASK, // 4124, 0x101c
	SCUI_UI_SCENE_SLEEP, // 4125, 0x101d
	SCUI_UI_SCENE_SLEEP_BODY, // 4126, 0x101e
	SCUI_UI_SCENE_SLEEP_TITLE, // 4127, 0x101f
	SCUI_UI_SCENE_SLEEP_HOUR, // 4128, 0x1020
	SCUI_UI_SCENE_SLEEP_UNIT, // 4129, 0x1021
	SCUI_UI_SCENE_SPO2, // 4130, 0x1022
	SCUI_UI_SCENE_SPO2_BODY, // 4131, 0x1023
	SCUI_UI_SCENE_SPO2_TITLE, // 4132, 0x1024
	SCUI_UI_SCENE_SPO2_VALUE, // 4133, 0x1025
	SCUI_UI_SCENE_SPO2_UNIT, // 4134, 0x1026
	SCUI_UI_SCENE_STRESS, // 4135, 0x1027
	SCUI_UI_SCENE_STRESS_BODY, // 4136, 0x1028
	SCUI_UI_SCENE_STRESS_TITLE, // 4137, 0x1029
	SCUI_UI_SCENE_STRESS_VALUE, // 4138, 0x102a
	SCUI_UI_SCENE_STRESS_LEVEL, // 4139, 0x102b
	SCUI_UI_SCENE_STRESS_TIME, // 4140, 0x102c
	SCUI_UI_SCENE_HONEYCOMB, // 4141, 0x102d
	SCUI_UI_SCENE_HONEYCOMB_SCROLL, // 4142, 0x102e
	SCUI_UI_SCENE_LIST_ARC, // 4143, 0x102f
	SCUI_UI_SCENE_LIST_ARC_SCROLL, // 4144, 0x1030
	SCUI_UI_SCENE_LIST_ARC_BAR_ARC, // 4145, 0x1031
	SCUI_UI_SCENE_LIST_ARC_MASK, // 4146, 0x1032
	SCUI_UI_SCENE_LIST_SCALE, // 4147, 0x1033
	SCUI_UI_SCENE_LIST_SCALE_BAR_ARC, // 4148, 0x1034
	SCUI_UI_SCENE_LIST_SCALE_MASK, // 4149, 0x1035
	SCUI_UI_SCENE_SPREAD, // 4150, 0x1036
	SCUI_UI_SCENE_SPREAD_CUSTOM, // 4151, 0x1037
	SCUI_UI_SCENE_THUMBWHEEL, // 4152, 0x1038
	SCUI_UI_SCENE_THUMBWHEEL_CUSTOM, // 4153, 0x1039
	SCUI_UI_SCENE_WATERFALL, // 4154, 0x103a
	SCUI_UI_SCENE_WATERFALL_SCROLL, // 4155, 0x103b
	SCUI_UI_SCENE_WATERFALL_BAR_ARC, // 4156, 0x103c
	SCUI_UI_SCENE_POPUP, // 4157, 0x103d
	SCUI_UI_SCENE_POPUP_SCALE, // 4158, 0x103e
	SCUI_UI_SCENE_POPUP_BG, // 4159, 0x103f
	SCUI_UI_SCENE_TEST_UI_BUTTON, // 4160, 0x1040
	SCUI_UI_SCENE_TEST_UI_CHART, // 4161, 0x1041
	SCUI_UI_SCENE_TEST_UI_CODE, // 4162, 0x1042
	SCUI_UI_SCENE_TEST_UI_CODE_1, // 4163, 0x1043
	SCUI_UI_SCENE_TEST_UI_CODE_2, // 4164, 0x1044
	SCUI_UI_SCENE_TEST_UI_GRAPH, // 4165, 0x1045
	SCUI_UI_SCENE_TEST_UI_GRAPH_1, // 4166, 0x1046
	SCUI_UI_SCENE_TEST_UI_GRAPH_2, // 4167, 0x1047
	SCUI_UI_SCENE_TEST_UI_GRAPH_3, // 4168, 0x1048
	SCUI_UI_SCENE_TEST_UI_GRAPH_4, // 4169, 0x1049
	SCUI_UI_SCENE_TEST_UI_GRAPH_5, // 4170, 0x104a
	SCUI_UI_SCENE_TEST_UI_GRAPH_6, // 4171, 0x104b
	SCUI_UI_SCENE_TEST_UI_GRAPH_7, // 4172, 0x104c
	SCUI_UI_SCENE_TEST_UI_GRAPH_8, // 4173, 0x104d
	SCUI_UI_SCENE_TEST_UI_GRAPH_9, // 4174, 0x104e
	SCUI_UI_SCENE_TEST_UI_ICON, // 4175, 0x104f
	SCUI_UI_SCENE_TEST_UI_INDEV_BAR, // 4176, 0x1050
	SCUI_UI_SCENE_TEST_UI_INDEV_BAR_1, // 4177, 0x1051
	SCUI_UI_SCENE_TEST_UI_INDEV_BAR_2, // 4178, 0x1052
	SCUI_UI_SCENE_TEST_UI_INDEV_ENC, // 4179, 0x1053
	SCUI_UI_SCENE_TEST_UI_INDEV_ENC_1, // 4180, 0x1054
	SCUI_UI_SCENE_TEST_UI_INDEV_ENC_2, // 4181, 0x1055
	SCUI_UI_SCENE_TEST_UI_INDEV_KEY, // 4182, 0x1056
	SCUI_UI_SCENE_TEST_UI_INDEV_KEY_1, // 4183, 0x1057
	SCUI_UI_SCENE_TEST_UI_INDEV_KEY_2, // 4184, 0x1058
	SCUI_UI_SCENE_TEST_UI_INDEV_PTR, // 4185, 0x1059
	SCUI_UI_SCENE_TEST_UI_INDEV_PTR_1, // 4186, 0x105a
	SCUI_UI_SCENE_TEST_UI_INDEV_PTR_2, // 4187, 0x105b
	SCUI_UI_SCENE_TEST_UI_LIST, // 4188, 0x105c
	SCUI_UI_SCENE_TEST_UI_LIST_SCROLL, // 4189, 0x105d
	SCUI_UI_SCENE_TEST_UI_LIST_ITEM_1, // 4190, 0x105e
	SCUI_UI_SCENE_TEST_UI_LIST_ITEM_2, // 4191, 0x105f
	SCUI_UI_SCENE_TEST_UI_LIST_ITEM_3, // 4192, 0x1060
	SCUI_UI_SCENE_TEST_UI_LIST_ITEM_4, // 4193, 0x1061
	SCUI_UI_SCENE_TEST_UI_LIST_ITEM_5, // 4194, 0x1062
	SCUI_UI_SCENE_TEST_UI_LIST_ITEM_6, // 4195, 0x1063
	SCUI_UI_SCENE_TEST_UI_LIST_ITEM_7, // 4196, 0x1064
	SCUI_UI_SCENE_TEST_UI_LIST_ITEM_8, // 4197, 0x1065
	SCUI_UI_SCENE_TEST_UI_LIST_ITEM_9, // 4198, 0x1066
	SCUI_UI_SCENE_TEST_UI_LIST_ITEM_10, // 4199, 0x1067
	SCUI_UI_SCENE_TEST_UI_LIST_ITEM_11, // 4200, 0x1068
	SCUI_UI_SCENE_TEST_UI_LIST_ITEM_12, // 4201, 0x1069
	SCUI_UI_SCENE_TEST_UI_LIST_ITEM_13, // 4202, 0x106a
	SCUI_UI_SCENE_TEST_UI_LIST_ITEM_14, // 4203, 0x106b
	SCUI_UI_SCENE_TEST_UI_LIST_ITEM_15, // 4204, 0x106c
	SCUI_UI_SCENE_TEST_UI_LIST_ITEM_16, // 4205, 0x106d
	SCUI_UI_SCENE_TEST_UI_MAIN, // 4206, 0x106e
	SCUI_UI_SCENE_TEST_UI_MAIN_HOME, // 4207, 0x106f
	SCUI_UI_SCENE_TEST_UI_MAIN_MONKEY, // 4208, 0x1070
	SCUI_UI_SCENE_TEST_UI_MAIN_MONITOR, // 4209, 0x1071
	SCUI_UI_SCENE_TEST_UI_MAIN_TEST, // 4210, 0x1072
	SCUI_UI_SCENE_TEST_UI_MISC, // 4211, 0x1073
	SCUI_UI_SCENE_TEST_UI_OBJECT, // 4212, 0x1074
	SCUI_UI_SCENE_TEST_UI_OBJECT_SCROLL, // 4213, 0x1075
	SCUI_UI_SCENE_TEST_UI_OBJECT_PAGE_1, // 4214, 0x1076
	SCUI_UI_SCENE_TEST_UI_OBJECT_PAGE_2, // 4215, 0x1077
	SCUI_UI_SCENE_TEST_UI_OBJECT_PAGE_3, // 4216, 0x1078
	SCUI_UI_SCENE_TEST_UI_RING, // 4217, 0x1079
	SCUI_UI_SCENE_TEST_UI_RING_CANVAS, // 4218, 0x107a
	SCUI_UI_SCENE_TEST_UI_ROLLER, // 4219, 0x107b
	SCUI_UI_SCENE_TEST_UI_SCROLL, // 4220, 0x107c
	SCUI_UI_SCENE_TEST_UI_STRING, // 4221, 0x107d
	SCUI_UI_SCENE_TEST_UI_SYMBOL, // 4222, 0x107e
	SCUI_UI_SCENE_TEST_UI_SYMBOL_CANVAS, // 4223, 0x107f
	SCUI_UI_SCENE_NONE, // 4224, 0x1080
	SCUI_UI_SCENE_NOTIFY, // 4225, 0x1081
	SCUI_UI_SCENE_QUICK_CARD, // 4226, 0x1082
	SCUI_UI_SCENE_STANDBY, // 4227, 0x1083
} scui_widget_parser_handle_t;

extern const void * const scui_widget_parser_table[132];

extern const scui_widget_json_key_t scui_widget_SCUI_UI_SCENE_BUTTERFLY_key;
extern const scui_widget_json_key_t scui_widget_SCUI_UI_SCENE_BUTTERFLY_CUSTOM_key;
extern const scui_widget_json_key_t scui_widget_SCUI_UI_SCENE_CUBE_key;
extern const scui_widget_json_key_t scui_widget_SCUI_UI_SCENE_CUBE_CUSTOM_key;
extern const scui_widget_json_key_t scui_widget_SCUI_UI_SCENE_LANTERN_key;
extern const scui_widget_json_key_t scui_widget_SCUI_UI_SCENE_LANTERN_CUSTOM_key;
extern const scui_widget_json_key_t scui_widget_SCUI_UI_SCENE_SOCCER_key;
extern const scui_widget_json_key_t scui_widget_SCUI_UI_SCENE_SOCCER_CUSTOM_key;
extern const scui_widget_json_key_t scui_widget_SCUI_UI_SCENE_ACTIVITY_key;
extern const scui_widget_json_key_t scui_widget_SCUI_UI_SCENE_ACTIVITY_SCROLL_key;
extern const scui_widget_json_key_t scui_widget_SCUI_UI_SCENE_ACTIVITY_BAR_ARC_key;
extern const scui_widget_json_key_t scui_widget_SCUI_UI_SCENE_ACTIVITY_SCROLL_RING_BIG_3_key;
extern const scui_widget_json_key_t scui_widget_SCUI_UI_SCENE_ACTIVITY_SCROLL_DITAIL_TITLE_key;
extern const scui_widget_json_key_t scui_widget_SCUI_UI_SCENE_ACTIVITY_SCROLL_DITAIL_SUM_key;
extern const scui_widget_json_key_t scui_widget_SCUI_UI_SCENE_ACTIVITY_SCROLL_DITAIL_KCAL_key;
extern const scui_widget_json_key_t scui_widget_SCUI_UI_SCENE_ACTIVITY_SCROLL_DITAIL_STEP_key;
extern const scui_widget_json_key_t scui_widget_SCUI_UI_SCENE_ACTIVITY_SCROLL_DITAIL_DIST_key;
extern const scui_widget_json_key_t scui_widget_SCUI_UI_SCENE_ACTIVITY_SCROLL_BLANK_key;
extern const scui_widget_json_key_t scui_widget_SCUI_UI_SCENE_HOME_key;
extern const scui_widget_json_key_t scui_widget_SCUI_UI_SCENE_HR_key;
extern const scui_widget_json_key_t scui_widget_SCUI_UI_SCENE_HR_BODY_key;
extern const scui_widget_json_key_t scui_widget_SCUI_UI_SCENE_HR_TITLE_key;
extern const scui_widget_json_key_t scui_widget_SCUI_UI_SCENE_HR_VALUE_key;
extern const scui_widget_json_key_t scui_widget_SCUI_UI_SCENE_HR_UNIT_key;
extern const scui_widget_json_key_t scui_widget_SCUI_UI_SCENE_HR_TIME_key;
extern const scui_widget_json_key_t scui_widget_SCUI_UI_SCENE_HR_BTN_TEXT_key;
extern const scui_widget_json_key_t scui_widget_SCUI_UI_SCENE_MINI_CARD_key;
extern const scui_widget_json_key_t scui_widget_SCUI_UI_SCENE_MINI_CARD_BAR_ARC_key;
extern const scui_widget_json_key_t scui_widget_SCUI_UI_SCENE_MINI_CARD_MASK_key;
extern const scui_widget_json_key_t scui_widget_SCUI_UI_SCENE_SLEEP_key;
extern const scui_widget_json_key_t scui_widget_SCUI_UI_SCENE_SLEEP_BODY_key;
extern const scui_widget_json_key_t scui_widget_SCUI_UI_SCENE_SLEEP_TITLE_key;
extern const scui_widget_json_key_t scui_widget_SCUI_UI_SCENE_SLEEP_HOUR_key;
extern const scui_widget_json_key_t scui_widget_SCUI_UI_SCENE_SLEEP_UNIT_key;
extern const scui_widget_json_key_t scui_widget_SCUI_UI_SCENE_SPO2_key;
extern const scui_widget_json_key_t scui_widget_SCUI_UI_SCENE_SPO2_BODY_key;
extern const scui_widget_json_key_t scui_widget_SCUI_UI_SCENE_SPO2_TITLE_key;
extern const scui_widget_json_key_t scui_widget_SCUI_UI_SCENE_SPO2_VALUE_key;
extern const scui_widget_json_key_t scui_widget_SCUI_UI_SCENE_SPO2_UNIT_key;
extern const scui_widget_json_key_t scui_widget_SCUI_UI_SCENE_STRESS_key;
extern const scui_widget_json_key_t scui_widget_SCUI_UI_SCENE_STRESS_BODY_key;
extern const scui_widget_json_key_t scui_widget_SCUI_UI_SCENE_STRESS_TITLE_key;
extern const scui_widget_json_key_t scui_widget_SCUI_UI_SCENE_STRESS_VALUE_key;
extern const scui_widget_json_key_t scui_widget_SCUI_UI_SCENE_STRESS_LEVEL_key;
extern const scui_widget_json_key_t scui_widget_SCUI_UI_SCENE_STRESS_TIME_key;
extern const scui_widget_json_key_t scui_widget_SCUI_UI_SCENE_HONEYCOMB_key;
extern const scui_widget_json_key_t scui_widget_SCUI_UI_SCENE_HONEYCOMB_SCROLL_key;
extern const scui_widget_json_key_t scui_widget_SCUI_UI_SCENE_LIST_ARC_key;
extern const scui_widget_json_key_t scui_widget_SCUI_UI_SCENE_LIST_ARC_SCROLL_key;
extern const scui_widget_json_key_t scui_widget_SCUI_UI_SCENE_LIST_ARC_BAR_ARC_key;
extern const scui_widget_json_key_t scui_widget_SCUI_UI_SCENE_LIST_ARC_MASK_key;
extern const scui_widget_json_key_t scui_widget_SCUI_UI_SCENE_LIST_SCALE_key;
extern const scui_widget_json_key_t scui_widget_SCUI_UI_SCENE_LIST_SCALE_BAR_ARC_key;
extern const scui_widget_json_key_t scui_widget_SCUI_UI_SCENE_LIST_SCALE_MASK_key;
extern const scui_widget_json_key_t scui_widget_SCUI_UI_SCENE_SPREAD_key;
extern const scui_widget_json_key_t scui_widget_SCUI_UI_SCENE_SPREAD_CUSTOM_key;
extern const scui_widget_json_key_t scui_widget_SCUI_UI_SCENE_THUMBWHEEL_key;
extern const scui_widget_json_key_t scui_widget_SCUI_UI_SCENE_THUMBWHEEL_CUSTOM_key;
extern const scui_widget_json_key_t scui_widget_SCUI_UI_SCENE_WATERFALL_key;
extern const scui_widget_json_key_t scui_widget_SCUI_UI_SCENE_WATERFALL_SCROLL_key;
extern const scui_widget_json_key_t scui_widget_SCUI_UI_SCENE_WATERFALL_BAR_ARC_key;
extern const scui_widget_json_key_t scui_widget_SCUI_UI_SCENE_POPUP_key;
extern const scui_widget_json_key_t scui_widget_SCUI_UI_SCENE_POPUP_SCALE_key;
extern const scui_widget_json_key_t scui_widget_SCUI_UI_SCENE_POPUP_BG_key;
extern const scui_widget_json_key_t scui_widget_SCUI_UI_SCENE_TEST_UI_BUTTON_key;
extern const scui_widget_json_key_t scui_widget_SCUI_UI_SCENE_TEST_UI_CHART_key;
extern const scui_widget_json_key_t scui_widget_SCUI_UI_SCENE_TEST_UI_CODE_key;
extern const scui_widget_json_key_t scui_widget_SCUI_UI_SCENE_TEST_UI_CODE_1_key;
extern const scui_widget_json_key_t scui_widget_SCUI_UI_SCENE_TEST_UI_CODE_2_key;
extern const scui_widget_json_key_t scui_widget_SCUI_UI_SCENE_TEST_UI_GRAPH_key;
extern const scui_widget_json_key_t scui_widget_SCUI_UI_SCENE_TEST_UI_GRAPH_1_key;
extern const scui_widget_json_key_t scui_widget_SCUI_UI_SCENE_TEST_UI_GRAPH_2_key;
extern const scui_widget_json_key_t scui_widget_SCUI_UI_SCENE_TEST_UI_GRAPH_3_key;
extern const scui_widget_json_key_t scui_widget_SCUI_UI_SCENE_TEST_UI_GRAPH_4_key;
extern const scui_widget_json_key_t scui_widget_SCUI_UI_SCENE_TEST_UI_GRAPH_5_key;
extern const scui_widget_json_key_t scui_widget_SCUI_UI_SCENE_TEST_UI_GRAPH_6_key;
extern const scui_widget_json_key_t scui_widget_SCUI_UI_SCENE_TEST_UI_GRAPH_7_key;
extern const scui_widget_json_key_t scui_widget_SCUI_UI_SCENE_TEST_UI_GRAPH_8_key;
extern const scui_widget_json_key_t scui_widget_SCUI_UI_SCENE_TEST_UI_GRAPH_9_key;
extern const scui_widget_json_key_t scui_widget_SCUI_UI_SCENE_TEST_UI_ICON_key;
extern const scui_widget_json_key_t scui_widget_SCUI_UI_SCENE_TEST_UI_INDEV_BAR_key;
extern const scui_widget_json_key_t scui_widget_SCUI_UI_SCENE_TEST_UI_INDEV_BAR_1_key;
extern const scui_widget_json_key_t scui_widget_SCUI_UI_SCENE_TEST_UI_INDEV_BAR_2_key;
extern const scui_widget_json_key_t scui_widget_SCUI_UI_SCENE_TEST_UI_INDEV_ENC_key;
extern const scui_widget_json_key_t scui_widget_SCUI_UI_SCENE_TEST_UI_INDEV_ENC_1_key;
extern const scui_widget_json_key_t scui_widget_SCUI_UI_SCENE_TEST_UI_INDEV_ENC_2_key;
extern const scui_widget_json_key_t scui_widget_SCUI_UI_SCENE_TEST_UI_INDEV_KEY_key;
extern const scui_widget_json_key_t scui_widget_SCUI_UI_SCENE_TEST_UI_INDEV_KEY_1_key;
extern const scui_widget_json_key_t scui_widget_SCUI_UI_SCENE_TEST_UI_INDEV_KEY_2_key;
extern const scui_widget_json_key_t scui_widget_SCUI_UI_SCENE_TEST_UI_INDEV_PTR_key;
extern const scui_widget_json_key_t scui_widget_SCUI_UI_SCENE_TEST_UI_INDEV_PTR_1_key;
extern const scui_widget_json_key_t scui_widget_SCUI_UI_SCENE_TEST_UI_INDEV_PTR_2_key;
extern const scui_widget_json_key_t scui_widget_SCUI_UI_SCENE_TEST_UI_LIST_key;
extern const scui_widget_json_key_t scui_widget_SCUI_UI_SCENE_TEST_UI_LIST_SCROLL_key;
extern const scui_widget_json_key_t scui_widget_SCUI_UI_SCENE_TEST_UI_LIST_ITEM_1_key;
extern const scui_widget_json_key_t scui_widget_SCUI_UI_SCENE_TEST_UI_LIST_ITEM_2_key;
extern const scui_widget_json_key_t scui_widget_SCUI_UI_SCENE_TEST_UI_LIST_ITEM_3_key;
extern const scui_widget_json_key_t scui_widget_SCUI_UI_SCENE_TEST_UI_LIST_ITEM_4_key;
extern const scui_widget_json_key_t scui_widget_SCUI_UI_SCENE_TEST_UI_LIST_ITEM_5_key;
extern const scui_widget_json_key_t scui_widget_SCUI_UI_SCENE_TEST_UI_LIST_ITEM_6_key;
extern const scui_widget_json_key_t scui_widget_SCUI_UI_SCENE_TEST_UI_LIST_ITEM_7_key;
extern const scui_widget_json_key_t scui_widget_SCUI_UI_SCENE_TEST_UI_LIST_ITEM_8_key;
extern const scui_widget_json_key_t scui_widget_SCUI_UI_SCENE_TEST_UI_LIST_ITEM_9_key;
extern const scui_widget_json_key_t scui_widget_SCUI_UI_SCENE_TEST_UI_LIST_ITEM_10_key;
extern const scui_widget_json_key_t scui_widget_SCUI_UI_SCENE_TEST_UI_LIST_ITEM_11_key;
extern const scui_widget_json_key_t scui_widget_SCUI_UI_SCENE_TEST_UI_LIST_ITEM_12_key;
extern const scui_widget_json_key_t scui_widget_SCUI_UI_SCENE_TEST_UI_LIST_ITEM_13_key;
extern const scui_widget_json_key_t scui_widget_SCUI_UI_SCENE_TEST_UI_LIST_ITEM_14_key;
extern const scui_widget_json_key_t scui_widget_SCUI_UI_SCENE_TEST_UI_LIST_ITEM_15_key;
extern const scui_widget_json_key_t scui_widget_SCUI_UI_SCENE_TEST_UI_LIST_ITEM_16_key;
extern const scui_widget_json_key_t scui_widget_SCUI_UI_SCENE_TEST_UI_MAIN_key;
extern const scui_widget_json_key_t scui_widget_SCUI_UI_SCENE_TEST_UI_MAIN_HOME_key;
extern const scui_widget_json_key_t scui_widget_SCUI_UI_SCENE_TEST_UI_MAIN_MONKEY_key;
extern const scui_widget_json_key_t scui_widget_SCUI_UI_SCENE_TEST_UI_MAIN_MONITOR_key;
extern const scui_widget_json_key_t scui_widget_SCUI_UI_SCENE_TEST_UI_MAIN_TEST_key;
extern const scui_widget_json_key_t scui_widget_SCUI_UI_SCENE_TEST_UI_MISC_key;
extern const scui_widget_json_key_t scui_widget_SCUI_UI_SCENE_TEST_UI_OBJECT_key;
extern const scui_widget_json_key_t scui_widget_SCUI_UI_SCENE_TEST_UI_OBJECT_SCROLL_key;
extern const scui_widget_json_key_t scui_widget_SCUI_UI_SCENE_TEST_UI_OBJECT_PAGE_1_key;
extern const scui_widget_json_key_t scui_widget_SCUI_UI_SCENE_TEST_UI_OBJECT_PAGE_2_key;
extern const scui_widget_json_key_t scui_widget_SCUI_UI_SCENE_TEST_UI_OBJECT_PAGE_3_key;
extern const scui_widget_json_key_t scui_widget_SCUI_UI_SCENE_TEST_UI_RING_key;
extern const scui_widget_json_key_t scui_widget_SCUI_UI_SCENE_TEST_UI_RING_CANVAS_key;
extern const scui_widget_json_key_t scui_widget_SCUI_UI_SCENE_TEST_UI_ROLLER_key;
extern const scui_widget_json_key_t scui_widget_SCUI_UI_SCENE_TEST_UI_SCROLL_key;
extern const scui_widget_json_key_t scui_widget_SCUI_UI_SCENE_TEST_UI_STRING_key;
extern const scui_widget_json_key_t scui_widget_SCUI_UI_SCENE_TEST_UI_SYMBOL_key;
extern const scui_widget_json_key_t scui_widget_SCUI_UI_SCENE_TEST_UI_SYMBOL_CANVAS_key;
extern const scui_widget_json_key_t scui_widget_SCUI_UI_SCENE_NONE_key;
extern const scui_widget_json_key_t scui_widget_SCUI_UI_SCENE_NOTIFY_key;
extern const scui_widget_json_key_t scui_widget_SCUI_UI_SCENE_QUICK_CARD_key;
extern const scui_widget_json_key_t scui_widget_SCUI_UI_SCENE_STANDBY_key;

#endif
