#ifndef SCUI_WIDGET_PARSER_H
#define SCUI_WIDGET_PARSER_H

/*一个通过scui_widget_parser脚本生成的widget表
 */

typedef enum {
	SCUI_HANDLE_OFFSET_WIDGET = 0x1000 - 1,
	SCUI_UI_SCENE_FLOAT_1,
	SCUI_UI_SCENE_FLOAT_1_C,
	SCUI_UI_SCENE_FLOAT_2,
	SCUI_UI_SCENE_FLOAT_2_C,
	SCUI_UI_SCENE_FLOAT_2_1,
	SCUI_UI_SCENE_FLOAT_2_2,
	SCUI_UI_SCENE_FLOAT_2_3,
	SCUI_UI_SCENE_FLOAT_2_4,
	SCUI_UI_SCENE_FLOAT_3,
	SCUI_UI_SCENE_FLOAT_3_RING,
	SCUI_UI_SCENE_FLOAT_4,
	SCUI_UI_SCENE_1,
	SCUI_UI_SCENE_1_PTR,
	SCUI_UI_SCENE_2,
	SCUI_UI_SCENE_3,
	SCUI_UI_SCENE_4,
	SCUI_UI_SCENE_5,
	SCUI_UI_SCENE_6,
	SCUI_UI_SCENE_6_C,
	SCUI_UI_SCENE_6_LU,
	SCUI_UI_SCENE_6_RU,
	SCUI_UI_SCENE_6_LD,
	SCUI_UI_SCENE_6_RD,
	SCUI_UI_SCENE_BUTTERFLY,
	SCUI_UI_SCENE_BUTTERFLY_CUSTOM,
	SCUI_UI_SCENE_CUBE,
	SCUI_UI_SCENE_CUBE_CUSTOM,
	SCUI_UI_SCENE_HOME,
	SCUI_UI_SCENE_LANTERN,
	SCUI_UI_SCENE_LANTERN_CUSTOM,
	SCUI_UI_SCENE_SOCCER,
	SCUI_UI_SCENE_SOCCER_CUSTOM,
	SCUI_UI_SCENE_TEST,
} scui_widget_parser_handle_t;

extern const void * scui_widget_parser_table[33];

#endif
