/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.7 */

#include "app_nanopb_flie.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(AppPB_FileDescriptor, AppPB_FileDescriptor, 2)


PB_BIND(AppPB_FilePackage, AppPB_FilePackage, 2)


PB_BIND(AppPB_File, AppPB_File, 2)



