# 这里简单打个包,将所有的文件搜索路径集中到此处
# 虽然依赖关系是线性向下的,但这里不打算对各个子库明细外部依赖

# 生成文件路径
set(app_adaptor_path
    ${CMAKE_CURRENT_SOURCE_DIR}/app_adaptor
    ${CMAKE_CURRENT_SOURCE_DIR}/app_adaptor/app_arch_adaptor
    ${CMAKE_CURRENT_SOURCE_DIR}/app_adaptor/app_arch_adaptor/app_arch_ext_mem
    ${CMAKE_CURRENT_SOURCE_DIR}/app_adaptor/app_arch_adaptor/app_arch_driver
    ${CMAKE_CURRENT_SOURCE_DIR}/app_adaptor/app_os_adaptor
    ${CMAKE_CURRENT_SOURCE_DIR}/app_adaptor/app_os_adaptor/app_os_ext_mem
)
set(app_sys_path
    ${CMAKE_CURRENT_SOURCE_DIR}/app_sys
    ${CMAKE_CURRENT_SOURCE_DIR}/app_sys/app_sys_log
    ${CMAKE_CURRENT_SOURCE_DIR}/app_sys/app_sys_pipe
    ${CMAKE_CURRENT_SOURCE_DIR}/app_sys/app_sys_ring_buffer
    ${CMAKE_CURRENT_SOURCE_DIR}/app_sys/app_sys_clock
    ${CMAKE_CURRENT_SOURCE_DIR}/app_sys/app_sys_timer
    ${CMAKE_CURRENT_SOURCE_DIR}/app_sys/app_sys_util
    ${CMAKE_CURRENT_SOURCE_DIR}/app_sys/app_sys_ext_mem
    ${CMAKE_CURRENT_SOURCE_DIR}/app_sys/app_sys_ext_src
)
set(app_third_path
    ${CMAKE_CURRENT_SOURCE_DIR}/app_third
    ${CMAKE_CURRENT_SOURCE_DIR}/app_third/lib_self
    ${CMAKE_CURRENT_SOURCE_DIR}/app_third/lib_self/app_third_calculator
    ${CMAKE_CURRENT_SOURCE_DIR}/app_third/lib_lvgl
    ${CMAKE_CURRENT_SOURCE_DIR}/app_third/lib_lvgl/lib_lvgl
)
set(app_thread_path
    ${CMAKE_CURRENT_SOURCE_DIR}/app_thread
    ${CMAKE_CURRENT_SOURCE_DIR}/app_thread/app_thread_master
    ${CMAKE_CURRENT_SOURCE_DIR}/app_thread/app_thread_master/app_thread_adaptor
    ${CMAKE_CURRENT_SOURCE_DIR}/app_thread/app_thread_master/app_module_vbus
    ${CMAKE_CURRENT_SOURCE_DIR}/app_thread/app_thread_master/app_module_system
    ${CMAKE_CURRENT_SOURCE_DIR}/app_thread/app_thread_master/app_module_watchdog
    ${CMAKE_CURRENT_SOURCE_DIR}/app_thread/app_thread_mix_irq
    ${CMAKE_CURRENT_SOURCE_DIR}/app_thread/app_thread_mix_irq/app_module_timer
    ${CMAKE_CURRENT_SOURCE_DIR}/app_thread/app_thread_mix_irq/app_module_clock
    ${CMAKE_CURRENT_SOURCE_DIR}/app_thread/app_thread_mix_irq/app_module_vibrate
    ${CMAKE_CURRENT_SOURCE_DIR}/app_thread/app_thread_mix_custom
    ${CMAKE_CURRENT_SOURCE_DIR}/app_thread/app_thread_mix_custom/app_module_alarm
    ${CMAKE_CURRENT_SOURCE_DIR}/app_thread/app_thread_mix_custom/app_module_countdown
    ${CMAKE_CURRENT_SOURCE_DIR}/app_thread/app_thread_mix_custom/app_module_stopwatch
    ${CMAKE_CURRENT_SOURCE_DIR}/app_thread/app_thread_mix_custom/app_module_world_time
    ${CMAKE_CURRENT_SOURCE_DIR}/app_thread/app_thread_mix_custom/app_module_drink_remind
    ${CMAKE_CURRENT_SOURCE_DIR}/app_thread/app_thread_mix_custom/app_module_do_not_disturb
    ${CMAKE_CURRENT_SOURCE_DIR}/app_thread/app_thread_data_manage
    ${CMAKE_CURRENT_SOURCE_DIR}/app_thread/app_thread_data_manage/app_module_data/app_module_trace
    ${CMAKE_CURRENT_SOURCE_DIR}/app_thread/app_thread_data_manage/app_module_data/app_module_dump
    ${CMAKE_CURRENT_SOURCE_DIR}/app_thread/app_thread_data_manage/app_module_data/app_module_load
    ${CMAKE_CURRENT_SOURCE_DIR}/app_thread/app_thread_data_manage/app_module_data/app_module_shutdown
    ${CMAKE_CURRENT_SOURCE_DIR}/app_thread/app_thread_data_manage/app_module_protocol/app_module_protocol
    ${CMAKE_CURRENT_SOURCE_DIR}/app_thread/app_thread_data_manage/app_module_protocol/app_module_transfer
    ${CMAKE_CURRENT_SOURCE_DIR}/app_thread/app_thread_data_manage/app_module_protocol/app_module_transfer_adaptor
    ${CMAKE_CURRENT_SOURCE_DIR}/app_thread/app_thread_lvgl
    ${CMAKE_CURRENT_SOURCE_DIR}/app_thread/app_thread_lvgl/app_lv_drv
    ${CMAKE_CURRENT_SOURCE_DIR}/app_thread/app_thread_lvgl/app_lv_ui
    ${CMAKE_CURRENT_SOURCE_DIR}/app_thread/app_thread_lvgl/app_lv_ui_scene
    ${CMAKE_CURRENT_SOURCE_DIR}/app_thread/app_thread_lvgl/app_lv_ui_scene/app_lv_ui_watch
    ${CMAKE_CURRENT_SOURCE_DIR}/app_thread/app_thread_lvgl/app_lv_ui_scene/app_lv_ui_group
    ${CMAKE_CURRENT_SOURCE_DIR}/app_thread/app_thread_lvgl/app_lv_ui_scene/app_lv_ui_custom
    ${CMAKE_CURRENT_SOURCE_DIR}/app_thread/app_thread_lvgl/app_lv_ui_scene/app_lv_ui_custom/app_lv_ui_clock
    ${CMAKE_CURRENT_SOURCE_DIR}/app_thread/app_thread_lvgl/app_lv_ui_scene/app_lv_ui_custom/app_lv_ui_calendar
    ${CMAKE_CURRENT_SOURCE_DIR}/app_thread/app_thread_lvgl/app_lv_ui_scene/app_lv_ui_custom/app_lv_ui_stopwatch
    ${CMAKE_CURRENT_SOURCE_DIR}/app_thread/app_thread_lvgl/app_lv_ui_scene/app_lv_ui_custom/app_lv_ui_countdown
    ${CMAKE_CURRENT_SOURCE_DIR}/app_thread/app_thread_lvgl/app_lv_ui_scene/app_lv_ui_custom/app_lv_ui_drink_remind
    ${CMAKE_CURRENT_SOURCE_DIR}/app_thread/app_thread_lvgl/app_lv_ui_scene/app_lv_ui_custom/app_lv_ui_calculator
    ${CMAKE_CURRENT_SOURCE_DIR}/app_thread/app_thread_lvgl/app_lv_ui_scene/app_lv_ui_custom/app_lv_ui_data_daily
)
set(app_main_path
    ${CMAKE_CURRENT_SOURCE_DIR}/app_main
)
# 编译器添加文件搜索路径
include_directories(${app_adaptor_path})
include_directories(${app_sys_path})
include_directories(${app_third_path})
include_directories(${app_thread_path})
include_directories(${app_main_path})
