/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.7 */

#ifndef PB_NANOPB_SRC_EMPTY_PB_H_INCLUDED
#define PB_NANOPB_SRC_EMPTY_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _EmptyEnum {
    EmptyEnum_EMPTY_DEFAULT = 0,
    EmptyEnum_EMPTY_NULL = 1,
    EmptyEnum_EMPTY_NONE = 2
} EmptyEnum;

/* Struct definitions */
typedef struct _EmptyMessage {
    char name[20];
    uint32_t data32;
    char distributor[100];
    EmptyEnum status;
} EmptyMessage;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _EmptyEnum_MIN EmptyEnum_EMPTY_DEFAULT
#define _EmptyEnum_MAX EmptyEnum_EMPTY_NONE
#define _EmptyEnum_ARRAYSIZE ((EmptyEnum)(EmptyEnum_EMPTY_NONE+1))

#define EmptyMessage_status_ENUMTYPE EmptyEnum


/* Initializer values for message structs */
#define EmptyMessage_init_default                {"", 0, "", _EmptyEnum_MIN}
#define EmptyMessage_init_zero                   {"", 0, "", _EmptyEnum_MIN}

/* Field tags (for use in manual encoding/decoding) */
#define EmptyMessage_name_tag                    1
#define EmptyMessage_data32_tag                  2
#define EmptyMessage_distributor_tag             3
#define EmptyMessage_status_tag                  4

/* Struct field encoding specification for nanopb */
#define EmptyMessage_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   name,              1) \
X(a, STATIC,   SINGULAR, UINT32,   data32,            2) \
X(a, STATIC,   SINGULAR, STRING,   distributor,       3) \
X(a, STATIC,   SINGULAR, UENUM,    status,            4)
#define EmptyMessage_CALLBACK NULL
#define EmptyMessage_DEFAULT NULL

extern const pb_msgdesc_t EmptyMessage_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define EmptyMessage_fields &EmptyMessage_msg

/* Maximum encoded size of messages (where known) */
#define EmptyMessage_size                        130

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
