/*实现目标:
 *    超时/空闲配置表
 */

#define SCUI_LOG_LOCAL_STATUS       1
#define SCUI_LOG_LOCAL_LEVEL        2   /* 0:DEBUG,1:INFO,2:WARN,3:ERROR,4:NONE */

#include "scui.h"

/* 超时/空闲表(给ui配置用的静态表, 新增界面在此登记一行即可)
 *   { 界面句柄值, 超时息屏时间, 超时返回主界面时间 }
 */
static const scui_check_time_t scui_check_time_table[] = {
    /* 默认项 */
    { SCUI_HANDLE_INVALID,            SCUI_CHECK_TIME_DEF, SCUI_CHECK_TIME_HOME_DEF },
    /* 主界面系(本身就在主界面, 无需返回) */
    { SCUI_UI_SCENE_HOME,             SCUI_CHECK_TIME_DEF, SCUI_OVERTIME_UNUSE },
    { SCUI_UI_SCENE_HOME_SW,          SCUI_CHECK_TIME_DEF, SCUI_OVERTIME_UNUSE },
    /* 表盘 */
    { SCUI_UI_SCENE_BUTTERFLY,        SCUI_CHECK_TIME_DEF, SCUI_CHECK_TIME_HOME_DEF },
    { SCUI_UI_SCENE_CUBE,             SCUI_CHECK_TIME_DEF, SCUI_CHECK_TIME_HOME_DEF },
    { SCUI_UI_SCENE_LANTERN,          SCUI_CHECK_TIME_DEF, SCUI_CHECK_TIME_HOME_DEF },
    { SCUI_UI_SCENE_SOCCER,           SCUI_CHECK_TIME_DEF, SCUI_CHECK_TIME_HOME_DEF },
    /* 健康 */
    { SCUI_UI_SCENE_ACTIVITY,         SCUI_CHECK_TIME_DEF, SCUI_CHECK_TIME_HOME_DEF },
    { SCUI_UI_SCENE_HR,               SCUI_CHECK_TIME_DEF, SCUI_CHECK_TIME_HOME_DEF },
    { SCUI_UI_SCENE_SLEEP,            SCUI_CHECK_TIME_DEF, SCUI_CHECK_TIME_HOME_DEF },
    { SCUI_UI_SCENE_SPO2,             SCUI_CHECK_TIME_DEF, SCUI_CHECK_TIME_HOME_DEF },
    { SCUI_UI_SCENE_STRESS,           SCUI_CHECK_TIME_DEF, SCUI_CHECK_TIME_HOME_DEF },
    { SCUI_UI_SCENE_MINI_CARD,        SCUI_CHECK_TIME_DEF, SCUI_CHECK_TIME_HOME_DEF },
    /* 列表/菜单 */
    { SCUI_UI_SCENE_HONEYCOMB,        SCUI_CHECK_TIME_DEF, SCUI_CHECK_TIME_HOME_DEF },
    { SCUI_UI_SCENE_LIST_ARC,         SCUI_CHECK_TIME_DEF, SCUI_CHECK_TIME_HOME_DEF },
    { SCUI_UI_SCENE_LIST_SCALE,       SCUI_CHECK_TIME_DEF, SCUI_CHECK_TIME_HOME_DEF },
    { SCUI_UI_SCENE_SPREAD,           SCUI_CHECK_TIME_DEF, SCUI_CHECK_TIME_HOME_DEF },
    { SCUI_UI_SCENE_THUMBWHEEL,       SCUI_CHECK_TIME_DEF, SCUI_CHECK_TIME_HOME_DEF },
    { SCUI_UI_SCENE_WATERFALL,        SCUI_CHECK_TIME_DEF, SCUI_CHECK_TIME_HOME_DEF },
    /* 测试 */
    { SCUI_UI_SCENE_TEST_UI_GRAPH,    SCUI_OVERTIME_UNUSE, SCUI_OVERTIME_UNUSE },
    { SCUI_UI_SCENE_TEST_UI_INDEV_BAR, SCUI_OVERTIME_UNUSE, SCUI_OVERTIME_UNUSE },
    { SCUI_UI_SCENE_TEST_UI_INDEV_ENC, SCUI_OVERTIME_UNUSE, SCUI_OVERTIME_UNUSE },
    { SCUI_UI_SCENE_TEST_UI_INDEV_KEY, SCUI_OVERTIME_UNUSE, SCUI_OVERTIME_UNUSE },
    { SCUI_UI_SCENE_TEST_UI_INDEV_PTR, SCUI_OVERTIME_UNUSE, SCUI_OVERTIME_UNUSE },
    { SCUI_UI_SCENE_TEST_UI_LAYOUT,   SCUI_OVERTIME_UNUSE, SCUI_OVERTIME_UNUSE },
    { SCUI_UI_SCENE_TEST_UI_LIST,     SCUI_OVERTIME_UNUSE, SCUI_OVERTIME_UNUSE },
    { SCUI_UI_SCENE_TEST_UI_MAIN,     SCUI_OVERTIME_UNUSE, SCUI_OVERTIME_UNUSE },
    { SCUI_UI_SCENE_TEST_UI_MISC,     SCUI_OVERTIME_UNUSE, SCUI_OVERTIME_UNUSE },
    { SCUI_UI_SCENE_TEST_UI_OBJECT,   SCUI_OVERTIME_UNUSE, SCUI_OVERTIME_UNUSE },
    { SCUI_UI_SCENE_TEST_UI_RING,     SCUI_OVERTIME_UNUSE, SCUI_OVERTIME_UNUSE },
    { SCUI_UI_SCENE_TEST_UI_ROLLER,   SCUI_OVERTIME_UNUSE, SCUI_OVERTIME_UNUSE },
    { SCUI_UI_SCENE_TEST_UI_SCROLL,   SCUI_OVERTIME_UNUSE, SCUI_OVERTIME_UNUSE },
    { SCUI_UI_SCENE_TEST_UI_STRING,   SCUI_OVERTIME_UNUSE, SCUI_OVERTIME_UNUSE },
    { SCUI_UI_SCENE_TEST_UI_SYMBOL,   SCUI_OVERTIME_UNUSE, SCUI_OVERTIME_UNUSE },
    { SCUI_UI_SCENE_TEST_UI_XIMAGE,   SCUI_OVERTIME_UNUSE, SCUI_OVERTIME_UNUSE },
};

/*@brief 超时/空闲配置表查找
 *@param handle 界面句柄值
 *@retval 配置项(未登记返回NULL)
 */
const scui_check_time_t * scui_check_time_find(scui_handle_t handle)
{
    for (uint8_t idx = 0; idx < scui_arr_len(scui_check_time_table); idx++) {
        if (scui_check_time_table[idx].handle == handle)
            return &scui_check_time_table[idx];
    }
    return NULL;
}
