/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.7 */

#ifndef PB_APP_NANOPB_SET_PB_H_INCLUDED
#define PB_APP_NANOPB_SET_PB_H_INCLUDED
#include <pb.h>
#include "app_nanopb_aux.pb.h"
#include "app_nanopb_mix.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
/* 组合消息(所有nanopb子消息打包成一个整体) */
typedef struct _AppPB_MsgSet {
    pb_size_t which_payload;
    union {
        /* 内部消息:0x01~0x20 */
        AppPB_ACK ack;
        /* 系统消息:0x21~0x50 */
        AppPB_TraceText trace_text;
        /* 功能消息:0x50~ */
        AppPB_SystemClock system_clock;
        AppPB_WorldClock world_clock;
    } payload;
} AppPB_MsgSet;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define AppPB_MsgSet_init_default                {0, {AppPB_ACK_init_default}}
#define AppPB_MsgSet_init_zero                   {0, {AppPB_ACK_init_zero}}

/* Field tags (for use in manual encoding/decoding) */
#define AppPB_MsgSet_ack_tag                     1
#define AppPB_MsgSet_trace_text_tag              33
#define AppPB_MsgSet_system_clock_tag            80
#define AppPB_MsgSet_world_clock_tag             81

/* Struct field encoding specification for nanopb */
#define AppPB_MsgSet_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,ack,payload.ack),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,trace_text,payload.trace_text),  33) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,system_clock,payload.system_clock),  80) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,world_clock,payload.world_clock),  81)
#define AppPB_MsgSet_CALLBACK NULL
#define AppPB_MsgSet_DEFAULT NULL
#define AppPB_MsgSet_payload_ack_MSGTYPE AppPB_ACK
#define AppPB_MsgSet_payload_trace_text_MSGTYPE AppPB_TraceText
#define AppPB_MsgSet_payload_system_clock_MSGTYPE AppPB_SystemClock
#define AppPB_MsgSet_payload_world_clock_MSGTYPE AppPB_WorldClock

extern const pb_msgdesc_t AppPB_MsgSet_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define AppPB_MsgSet_fields &AppPB_MsgSet_msg

/* Maximum encoded size of messages (where known) */
#define AppPB_MsgSet_size                        141

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
