/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.7 */

#ifndef PB_APP_NANOPB_MIX_PB_H_INCLUDED
#define PB_APP_NANOPB_MIX_PB_H_INCLUDED
#include <pb.h>
#include "nanopb/nanopb.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
/* 系统时钟制式 */
typedef enum _AppPB_SystemClock_Mode {
    AppPB_SystemClock_Mode_IS_24 = 0,
    AppPB_SystemClock_Mode_IS_12 = 1
} AppPB_SystemClock_Mode;

/* Struct definitions */
/* 系统时钟消息(日历时间) */
typedef struct _AppPB_SystemClock {
    uint16_t year; /* 年(UTC的0时区) */
    uint8_t month; /* 月(UTC的0时区) */
    uint8_t day; /* 日(UTC的0时区) */
    uint8_t hour; /* 时(UTC的0时区) */
    uint8_t minute; /* 分(UTC的0时区) */
    uint8_t second; /* 秒(UTC的0时区) */
    int32_t zone; /* 时区偏移(秒),带符号 */
    AppPB_SystemClock_Mode mode;
} AppPB_SystemClock;

/* 追踪日志消息文本最大限制 APP_SYS_TRACE_TEXT_MAX + 1 */
typedef struct _AppPB_TraceText {
    char trace_text[129]; /* 单条传输文本消息 */
} AppPB_TraceText;

/* 这里携带俩个额外的参数确定世界时钟数量以及当前世界时钟位置 */
typedef struct _AppPB_WorldClock {
    uint8_t now_index; /* 世界时钟当前索引 */
    uint8_t max_count; /* 世界时钟数量 */
    char city_name[100]; /* 城市名称 */
    int32_t zone_offset; /* 时区偏移(秒),带符号 */
    double longitude; /* 经度:东经+,西经- */
    double latitude; /* 维度:北纬+,南纬- */
    uint32_t city_id; /* 城市ID */
} AppPB_WorldClock;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _AppPB_SystemClock_Mode_MIN AppPB_SystemClock_Mode_IS_24
#define _AppPB_SystemClock_Mode_MAX AppPB_SystemClock_Mode_IS_12
#define _AppPB_SystemClock_Mode_ARRAYSIZE ((AppPB_SystemClock_Mode)(AppPB_SystemClock_Mode_IS_12+1))

#define AppPB_SystemClock_mode_ENUMTYPE AppPB_SystemClock_Mode




/* Initializer values for message structs */
#define AppPB_SystemClock_init_default           {0, 0, 0, 0, 0, 0, 0, _AppPB_SystemClock_Mode_MIN}
#define AppPB_TraceText_init_default             {""}
#define AppPB_WorldClock_init_default            {0, 0, "", 0, 0, 0, 0}
#define AppPB_SystemClock_init_zero              {0, 0, 0, 0, 0, 0, 0, _AppPB_SystemClock_Mode_MIN}
#define AppPB_TraceText_init_zero                {""}
#define AppPB_WorldClock_init_zero               {0, 0, "", 0, 0, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define AppPB_SystemClock_year_tag               1
#define AppPB_SystemClock_month_tag              2
#define AppPB_SystemClock_day_tag                3
#define AppPB_SystemClock_hour_tag               4
#define AppPB_SystemClock_minute_tag             5
#define AppPB_SystemClock_second_tag             6
#define AppPB_SystemClock_zone_tag               7
#define AppPB_SystemClock_mode_tag               8
#define AppPB_TraceText_trace_text_tag           1
#define AppPB_WorldClock_now_index_tag           1
#define AppPB_WorldClock_max_count_tag           2
#define AppPB_WorldClock_city_name_tag           3
#define AppPB_WorldClock_zone_offset_tag         4
#define AppPB_WorldClock_longitude_tag           5
#define AppPB_WorldClock_latitude_tag            6
#define AppPB_WorldClock_city_id_tag             7

/* Struct field encoding specification for nanopb */
#define AppPB_SystemClock_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT64,   year,              1) \
X(a, STATIC,   SINGULAR, UINT64,   month,             2) \
X(a, STATIC,   SINGULAR, UINT64,   day,               3) \
X(a, STATIC,   SINGULAR, UINT64,   hour,              4) \
X(a, STATIC,   SINGULAR, UINT64,   minute,            5) \
X(a, STATIC,   SINGULAR, UINT64,   second,            6) \
X(a, STATIC,   SINGULAR, SINT64,   zone,              7) \
X(a, STATIC,   SINGULAR, UENUM,    mode,              8)
#define AppPB_SystemClock_CALLBACK NULL
#define AppPB_SystemClock_DEFAULT NULL

#define AppPB_TraceText_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   trace_text,        1)
#define AppPB_TraceText_CALLBACK NULL
#define AppPB_TraceText_DEFAULT NULL

#define AppPB_WorldClock_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   now_index,         1) \
X(a, STATIC,   SINGULAR, UINT32,   max_count,         2) \
X(a, STATIC,   SINGULAR, STRING,   city_name,         3) \
X(a, STATIC,   SINGULAR, SINT64,   zone_offset,       4) \
X(a, STATIC,   SINGULAR, DOUBLE,   longitude,         5) \
X(a, STATIC,   SINGULAR, DOUBLE,   latitude,          6) \
X(a, STATIC,   SINGULAR, UINT32,   city_id,           7)
#define AppPB_WorldClock_CALLBACK NULL
#define AppPB_WorldClock_DEFAULT NULL

extern const pb_msgdesc_t AppPB_SystemClock_msg;
extern const pb_msgdesc_t AppPB_TraceText_msg;
extern const pb_msgdesc_t AppPB_WorldClock_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define AppPB_SystemClock_fields &AppPB_SystemClock_msg
#define AppPB_TraceText_fields &AppPB_TraceText_msg
#define AppPB_WorldClock_fields &AppPB_WorldClock_msg

/* Maximum encoded size of messages (where known) */
#define AppPB_SystemClock_size                   27
#define AppPB_TraceText_size                     131
#define AppPB_WorldClock_size                    137

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
